// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: admin.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const approveRestaurant = `-- name: ApproveRestaurant :one
UPDATE restaurants
SET is_approved = $1::boolean,
    updated_at = now()
WHERE id = $2::int
RETURNING id, name, is_approved
`

type ApproveRestaurantParams struct {
	IsApproved   bool  `json:"isApproved"`
	RestaurantID int32 `json:"restaurantId"`
}

type ApproveRestaurantRow struct {
	ID         int32  `json:"id"`
	Name       string `json:"name"`
	IsApproved *bool  `json:"isApproved"`
}

func (q *Queries) ApproveRestaurant(ctx context.Context, db DBTX, arg *ApproveRestaurantParams) (*ApproveRestaurantRow, error) {
	row := db.QueryRow(ctx, approveRestaurant, arg.IsApproved, arg.RestaurantID)
	var i ApproveRestaurantRow
	err := row.Scan(&i.ID, &i.Name, &i.IsApproved)
	return &i, err
}

const getAllUsers = `-- name: GetAllUsers :many
SELECT
    u.id,
    u.username,
    u.email,
    u.display_name,
    u.avatar_url,
    u.created_at,
    u.updated_at,
    u.status
FROM users u
ORDER BY u.created_at DESC
LIMIT $1 OFFSET $2
`

type GetAllUsersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type GetAllUsersRow struct {
	ID          string             `json:"id"`
	Username    string             `json:"username"`
	Email       string             `json:"email"`
	DisplayName string             `json:"displayName"`
	AvatarUrl   *string            `json:"avatarUrl"`
	CreatedAt   pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt   pgtype.Timestamptz `json:"updatedAt"`
	Status      string             `json:"status"`
}

func (q *Queries) GetAllUsers(ctx context.Context, db DBTX, arg *GetAllUsersParams) ([]*GetAllUsersRow, error) {
	rows, err := db.Query(ctx, getAllUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GetAllUsersRow{}
	for rows.Next() {
		var i GetAllUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.DisplayName,
			&i.AvatarUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRestaurantsAdmin = `-- name: GetRestaurantsAdmin :many
SELECT
    r.id,
    r.name,
    r.description,
    r.avatar_url,
    r.username,
    r.email,
    r.phone,
    r.address,
    r.lat,
    r.lng,
    r.created_at,
    r.updated_at,
    r.is_approved,
    u.id as owner_id,
    u.username as owner_username,
    u.display_name as owner_name,
    u.email as owner_email
FROM restaurants r
LEFT JOIN restaurant_manager rm ON r.id = rm.restaurant_id AND rm.is_owner = true
LEFT JOIN users u ON rm.user_id = u.id
ORDER BY r.created_at DESC
LIMIT $1 OFFSET $2
`

type GetRestaurantsAdminParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type GetRestaurantsAdminRow struct {
	ID            int32              `json:"id"`
	Name          string             `json:"name"`
	Description   *string            `json:"description"`
	AvatarUrl     *string            `json:"avatarUrl"`
	Username      string             `json:"username"`
	Email         *string            `json:"email"`
	Phone         *string            `json:"phone"`
	Address       *string            `json:"address"`
	Lat           *float64           `json:"lat"`
	Lng           *float64           `json:"lng"`
	CreatedAt     pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt     pgtype.Timestamptz `json:"updatedAt"`
	IsApproved    *bool              `json:"isApproved"`
	OwnerID       *string            `json:"ownerId"`
	OwnerUsername *string            `json:"ownerUsername"`
	OwnerName     *string            `json:"ownerName"`
	OwnerEmail    *string            `json:"ownerEmail"`
}

func (q *Queries) GetRestaurantsAdmin(ctx context.Context, db DBTX, arg *GetRestaurantsAdminParams) ([]*GetRestaurantsAdminRow, error) {
	rows, err := db.Query(ctx, getRestaurantsAdmin, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GetRestaurantsAdminRow{}
	for rows.Next() {
		var i GetRestaurantsAdminRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.AvatarUrl,
			&i.Username,
			&i.Email,
			&i.Phone,
			&i.Address,
			&i.Lat,
			&i.Lng,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsApproved,
			&i.OwnerID,
			&i.OwnerUsername,
			&i.OwnerName,
			&i.OwnerEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setUserStatus = `-- name: SetUserStatus :exec
UPDATE users
SET status = $1::varchar,
    updated_at = now()
WHERE id = $2::varchar
`

type SetUserStatusParams struct {
	Status string `json:"status"`
	UserID string `json:"userId"`
}

func (q *Queries) SetUserStatus(ctx context.Context, db DBTX, arg *SetUserStatusParams) error {
	_, err := db.Exec(ctx, setUserStatus, arg.Status, arg.UserID)
	return err
}
