// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: cuisines.sql

package database

import (
	"context"
)

const addCuisine = `-- name: AddCuisine :one
INSERT INTO cuisines (name, parent_id, image_url)
VALUES ($1,$2,$3)
RETURNING id, name, parent_id, image_url, created_at, updated_at
`

type AddCuisineParams struct {
	Name     string  `json:"name"`
	ParentID *int16  `json:"parentId"`
	ImageUrl *string `json:"imageUrl"`
}

func (q *Queries) AddCuisine(ctx context.Context, db DBTX, arg *AddCuisineParams) (*Cuisine, error) {
	row := db.QueryRow(ctx, addCuisine, arg.Name, arg.ParentID, arg.ImageUrl)
	var i Cuisine
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ParentID,
		&i.ImageUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const deleteCuisine = `-- name: DeleteCuisine :exec
DELETE FROM cuisines
WHERE id = $1
`

func (q *Queries) DeleteCuisine(ctx context.Context, db DBTX, id int16) error {
	_, err := db.Exec(ctx, deleteCuisine, id)
	return err
}

const getCuisineRecursionById = `-- name: GetCuisineRecursionById :many
WITH RECURSIVE cuisine_tree AS (
    SELECT
        c1.id,
        c1.name,
        c1.image_url,
        c1.parent_id,
        1::float AS level,
        0::float AS w
    FROM cuisines c1
    WHERE COALESCE($1, 0) = c1.id
    UNION ALL
    SELECT
        c.id,
        c."name",
        c.image_url,
        c.parent_id,
        ct.level * 0.01 AS level,
        ct.w + ct.level * 0.01 * ROW_NUMBER() OVER (PARTITION BY c.parent_id ORDER BY c.id) AS w
    FROM cuisines c
             INNER JOIN cuisine_tree ct ON c.parent_id = ct.id
)
SELECT id, name, image_url, parent_id, level, w FROM cuisine_tree
order by level desc, w, id
`

type GetCuisineRecursionByIdRow struct {
	ID       int16   `json:"id"`
	Name     string  `json:"name"`
	ImageUrl *string `json:"imageUrl"`
	ParentID *int16  `json:"parentId"`
	Level    float64 `json:"level"`
	W        float64 `json:"w"`
}

func (q *Queries) GetCuisineRecursionById(ctx context.Context, db DBTX, id int16) ([]*GetCuisineRecursionByIdRow, error) {
	rows, err := db.Query(ctx, getCuisineRecursionById, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GetCuisineRecursionByIdRow{}
	for rows.Next() {
		var i GetCuisineRecursionByIdRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ImageUrl,
			&i.ParentID,
			&i.Level,
			&i.W,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCuisine = `-- name: UpdateCuisine :one
UPDATE cuisines
SET name = $2,
    parent_id = $3,
    image_url = $4,
    updated_at = NOW()
WHERE id = $1
RETURNING id, name, parent_id, image_url, created_at, updated_at
`

type UpdateCuisineParams struct {
	ID       int16   `json:"id"`
	Name     string  `json:"name"`
	ParentID *int16  `json:"parentId"`
	ImageUrl *string `json:"imageUrl"`
}

func (q *Queries) UpdateCuisine(ctx context.Context, db DBTX, arg *UpdateCuisineParams) (*Cuisine, error) {
	row := db.QueryRow(ctx, updateCuisine,
		arg.ID,
		arg.Name,
		arg.ParentID,
		arg.ImageUrl,
	)
	var i Cuisine
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ParentID,
		&i.ImageUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
