// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: dishes.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDish = `-- name: CreateDish :one
WITH inserted_dish AS (
    INSERT INTO dishes (restaurant_id, name, description, price, cuisine_id)
    VALUES(
        $1::int,
        $2::varchar(255),
        $3::text,
        $4::bigint,
        $5::smallint)
    RETURNING id, name, description, price, cuisine_id, restaurant_id, created_at, updated_at
)
SELECT
    d.id,
    d.name,
    d.description,
    d.price,
    d.restaurant_id,
    r.name AS restaurant,
    r.address,
    r.lat,
    r.lng,
    d.cuisine_id,
    c.name AS cuisine,
    d.created_at,
    d.updated_at
FROM inserted_dish d
LEFT JOIN restaurants r ON r.id = d.restaurant_id
LEFT JOIN cuisines    c ON c.id = d.cuisine_id
`

type CreateDishParams struct {
	RestaurantID *int32  `json:"restaurantId"`
	Name         *string `json:"name"`
	Description  *string `json:"description"`
	Price        *int64  `json:"price"`
	CuisineID    *int16  `json:"cuisineId"`
}

type CreateDishRow struct {
	ID           int32              `json:"id"`
	Name         string             `json:"name"`
	Description  *string            `json:"description"`
	Price        int64              `json:"price"`
	RestaurantID int32              `json:"restaurantId"`
	Restaurant   *string            `json:"restaurant"`
	Address      *string            `json:"address"`
	Lat          *float64           `json:"lat"`
	Lng          *float64           `json:"lng"`
	CuisineID    int16              `json:"cuisineId"`
	Cuisine      *string            `json:"cuisine"`
	CreatedAt    pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt    pgtype.Timestamptz `json:"updatedAt"`
}

func (q *Queries) CreateDish(ctx context.Context, db DBTX, arg *CreateDishParams) (*CreateDishRow, error) {
	row := db.QueryRow(ctx, createDish,
		arg.RestaurantID,
		arg.Name,
		arg.Description,
		arg.Price,
		arg.CuisineID,
	)
	var i CreateDishRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.RestaurantID,
		&i.Restaurant,
		&i.Address,
		&i.Lat,
		&i.Lng,
		&i.CuisineID,
		&i.Cuisine,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const deleteDish = `-- name: DeleteDish :exec
DELETE FROM dishes WHERE id = $1
`

func (q *Queries) DeleteDish(ctx context.Context, db DBTX, id int32) error {
	_, err := db.Exec(ctx, deleteDish, id)
	return err
}

const getDishByID = `-- name: GetDishByID :one
SELECT
    d.id,
    d.name,
    d.description,
    d.price,
    d.restaurant_id,
    r.name as restaurant,
    r.address,
    r.lat,
    r.lng,
    d.cuisine_id,
    c.name as cuisine,
    d.created_at,
    d.updated_at
FROM dishes d
LEFT JOIN restaurants r ON r.id = d.restaurant_id
LEFT JOIN cuisines c ON c.id = d.cuisine_id
WHERE d.id = $1
`

type GetDishByIDRow struct {
	ID           int32              `json:"id"`
	Name         string             `json:"name"`
	Description  *string            `json:"description"`
	Price        int64              `json:"price"`
	RestaurantID int32              `json:"restaurantId"`
	Restaurant   *string            `json:"restaurant"`
	Address      *string            `json:"address"`
	Lat          *float64           `json:"lat"`
	Lng          *float64           `json:"lng"`
	CuisineID    int16              `json:"cuisineId"`
	Cuisine      *string            `json:"cuisine"`
	CreatedAt    pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt    pgtype.Timestamptz `json:"updatedAt"`
}

func (q *Queries) GetDishByID(ctx context.Context, db DBTX, id int32) (*GetDishByIDRow, error) {
	row := db.QueryRow(ctx, getDishByID, id)
	var i GetDishByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.RestaurantID,
		&i.Restaurant,
		&i.Address,
		&i.Lat,
		&i.Lng,
		&i.CuisineID,
		&i.Cuisine,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getDishes = `-- name: GetDishes :many
SELECT
    d.id,
    d.name,
    d.description,
    d.price,
    d.restaurant_id,
    r.name as restaurant,
    r.address,
    r.lat,
    r.lng,
    d.cuisine_id,
    c.name as cuisine,
    d.created_at,
    d.updated_at
FROM dishes d
LEFT JOIN restaurants r ON r.id = d.restaurant_id
LEFT JOIN cuisines c ON c.id = d.cuisine_id
WHERE
    ($3::int is null or d.restaurant_id = $3::int)
  and
    d.cuisine_id in (select id from get_cuisine_recursion_by_id($4::smallint))
ORDER BY d.updated_at DESC
LIMIT $1 OFFSET $2
`

type GetDishesParams struct {
	Limit        int32  `json:"limit"`
	Offset       int32  `json:"offset"`
	RestaurantID *int32 `json:"restaurantId"`
	CuisineID    *int16 `json:"cuisineId"`
}

type GetDishesRow struct {
	ID           int32              `json:"id"`
	Name         string             `json:"name"`
	Description  *string            `json:"description"`
	Price        int64              `json:"price"`
	RestaurantID int32              `json:"restaurantId"`
	Restaurant   *string            `json:"restaurant"`
	Address      *string            `json:"address"`
	Lat          *float64           `json:"lat"`
	Lng          *float64           `json:"lng"`
	CuisineID    int16              `json:"cuisineId"`
	Cuisine      *string            `json:"cuisine"`
	CreatedAt    pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt    pgtype.Timestamptz `json:"updatedAt"`
}

func (q *Queries) GetDishes(ctx context.Context, db DBTX, arg *GetDishesParams) ([]*GetDishesRow, error) {
	rows, err := db.Query(ctx, getDishes,
		arg.Limit,
		arg.Offset,
		arg.RestaurantID,
		arg.CuisineID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GetDishesRow{}
	for rows.Next() {
		var i GetDishesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Price,
			&i.RestaurantID,
			&i.Restaurant,
			&i.Address,
			&i.Lat,
			&i.Lng,
			&i.CuisineID,
			&i.Cuisine,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
