// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: dishes.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDish = `-- name: CreateDish :one
WITH inserted_dish AS (
    INSERT INTO dishes (restaurant_id, name, description, price, cuisine_id)
    VALUES
        ($1, $2, $3, $4, $5)
    RETURNING id, name, description, price, cuisine_id, restaurant_id, created_at, updated_at
)
SELECT
    d.id,
    d.name,
    d.description,
    d.price,
    d.restaurant_id,
    r.name AS restaurant,
    r.address,
    r.lat,
    r.lng,
    d.cuisine_id,
    c.name AS cuisine,
    d.created_at,
    d.updated_at
FROM inserted_dish d
LEFT JOIN restaurants r ON r.id = d.restaurant_id
LEFT JOIN cuisines    c ON c.id = d.cuisine_id
`

type CreateDishParams struct {
	RestaurantID int32   `json:"restaurantId"`
	Name         string  `json:"name"`
	Description  *string `json:"description"`
	Price        int64   `json:"price"`
	CuisineID    int16   `json:"cuisineId"`
}

type CreateDishRow struct {
	ID           int32              `json:"id"`
	Name         string             `json:"name"`
	Description  *string            `json:"description"`
	Price        int64              `json:"price"`
	RestaurantID int32              `json:"restaurantId"`
	Restaurant   *string            `json:"restaurant"`
	Address      *string            `json:"address"`
	Lat          *float64           `json:"lat"`
	Lng          *float64           `json:"lng"`
	CuisineID    int16              `json:"cuisineId"`
	Cuisine      *string            `json:"cuisine"`
	CreatedAt    pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt    pgtype.Timestamptz `json:"updatedAt"`
}

func (q *Queries) CreateDish(ctx context.Context, db DBTX, arg *CreateDishParams) (*CreateDishRow, error) {
	row := db.QueryRow(ctx, createDish,
		arg.RestaurantID,
		arg.Name,
		arg.Description,
		arg.Price,
		arg.CuisineID,
	)
	var i CreateDishRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.RestaurantID,
		&i.Restaurant,
		&i.Address,
		&i.Lat,
		&i.Lng,
		&i.CuisineID,
		&i.Cuisine,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const deleteFood = `-- name: DeleteFood :exec


DELETE FROM dishes WHERE id = $1
`

// -- name: UpdateDish :one
// WITH inserted_dish AS (
//
//	UPDATE dishes
//	SET name = coalesce($1, name),
//	    description = coalesce($2, description),
//	    price = coalesce($3, price),
//	    cuisine_id = coalesce($4, cuisine_id),
//	    updated_at = now()
//	WHERE id = $5
//	RETURNING *
//
// )
// SELECT
//
//	d.id,
//	d.name,
//	d.description,
//	d.price,
//	d.restaurant_id,
//	r.name AS restaurant,
//	r.address,
//	r.lat,
//	r.lng,
//	d.cuisine_id,
//	c.name AS cuisine,
//	d.created_at,
//	d.updated_at
//
// FROM inserted_dish d
// LEFT JOIN restaurants r ON r.id = d.restaurant_id
// LEFT JOIN cuisines    c ON c.id = d.cuisine_id;
func (q *Queries) DeleteFood(ctx context.Context, db DBTX, id int32) error {
	_, err := db.Exec(ctx, deleteFood, id)
	return err
}

const getDishByID = `-- name: GetDishByID :one
SELECT
    d.id,
    d.name,
    d.description,
    d.price,
    d.restaurant_id,
    r.name as restaurant,
    r.address,
    r.lat,
    r.lng,
    d.cuisine_id,
    c.name as cuisine,
    d.created_at,
    d.updated_at
FROM dishes d
LEFT JOIN restaurants r ON r.id = d.restaurant_id
LEFT JOIN cuisines c ON c.id = d.cuisine_id
WHERE d.id = $1
`

type GetDishByIDRow struct {
	ID           int32              `json:"id"`
	Name         string             `json:"name"`
	Description  *string            `json:"description"`
	Price        int64              `json:"price"`
	RestaurantID int32              `json:"restaurantId"`
	Restaurant   *string            `json:"restaurant"`
	Address      *string            `json:"address"`
	Lat          *float64           `json:"lat"`
	Lng          *float64           `json:"lng"`
	CuisineID    int16              `json:"cuisineId"`
	Cuisine      *string            `json:"cuisine"`
	CreatedAt    pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt    pgtype.Timestamptz `json:"updatedAt"`
}

func (q *Queries) GetDishByID(ctx context.Context, db DBTX, id int32) (*GetDishByIDRow, error) {
	row := db.QueryRow(ctx, getDishByID, id)
	var i GetDishByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.RestaurantID,
		&i.Restaurant,
		&i.Address,
		&i.Lat,
		&i.Lng,
		&i.CuisineID,
		&i.Cuisine,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const listFoodsByRestaurant = `-- name: ListFoodsByRestaurant :many
SELECT
    d.id,
    d.name,
    d.description,
    d.price,
    d.restaurant_id,
    r.name as restaurant,
    r.address,
    r.lat,
    r.lng,
    d.cuisine_id,
    c.name as cuisine,
    d.created_at,
    d.updated_at
FROM dishes d
LEFT JOIN restaurants r ON r.id = d.restaurant_id
LEFT JOIN cuisines c ON c.id = d.cuisine_id
WHERE d.restaurant_id = $1
ORDER BY d.updated_at DESC
LIMIT $2 OFFSET $3
`

type ListFoodsByRestaurantParams struct {
	RestaurantID int32 `json:"restaurantId"`
	Limit        int32 `json:"limit"`
	Offset       int32 `json:"offset"`
}

type ListFoodsByRestaurantRow struct {
	ID           int32              `json:"id"`
	Name         string             `json:"name"`
	Description  *string            `json:"description"`
	Price        int64              `json:"price"`
	RestaurantID int32              `json:"restaurantId"`
	Restaurant   *string            `json:"restaurant"`
	Address      *string            `json:"address"`
	Lat          *float64           `json:"lat"`
	Lng          *float64           `json:"lng"`
	CuisineID    int16              `json:"cuisineId"`
	Cuisine      *string            `json:"cuisine"`
	CreatedAt    pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt    pgtype.Timestamptz `json:"updatedAt"`
}

func (q *Queries) ListFoodsByRestaurant(ctx context.Context, db DBTX, arg *ListFoodsByRestaurantParams) ([]*ListFoodsByRestaurantRow, error) {
	rows, err := db.Query(ctx, listFoodsByRestaurant, arg.RestaurantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*ListFoodsByRestaurantRow{}
	for rows.Next() {
		var i ListFoodsByRestaurantRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Price,
			&i.RestaurantID,
			&i.Restaurant,
			&i.Address,
			&i.Lat,
			&i.Lng,
			&i.CuisineID,
			&i.Cuisine,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
