// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: interaction.sql

package database

import (
	"context"
)

const addInteraction = `-- name: AddInteraction :exec
INSERT  INTO user_interactions(user_id, dish_id)
VALUES ($1, $2)
`

type AddInteractionParams struct {
	UserID interface{} `json:"userId"`
	DishID int32       `json:"dishId"`
}

func (q *Queries) AddInteraction(ctx context.Context, db DBTX, arg *AddInteractionParams) error {
	_, err := db.Exec(ctx, addInteraction, arg.UserID, arg.DishID)
	return err
}
