// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: menu.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMenuCategory = `-- name: CreateMenuCategory :one
INSERT INTO menu_categories (name, restaurant_id)
VALUES ($1, $2)
RETURNING id, name, restaurant_id, created_at, updated_at
`

type CreateMenuCategoryParams struct {
	Name         *string `json:"name"`
	RestaurantID *int32  `json:"restaurantId"`
}

func (q *Queries) CreateMenuCategory(ctx context.Context, db DBTX, arg *CreateMenuCategoryParams) (*MenuCategory, error) {
	row := db.QueryRow(ctx, createMenuCategory, arg.Name, arg.RestaurantID)
	var i MenuCategory
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.RestaurantID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const deleteMenuCategoryById = `-- name: DeleteMenuCategoryById :exec
DELETE FROM menu_categories
WHERE id = $1
`

func (q *Queries) DeleteMenuCategoryById(ctx context.Context, db DBTX, id int32) error {
	_, err := db.Exec(ctx, deleteMenuCategoryById, id)
	return err
}

const getDishesByRestaurant = `-- name: GetDishesByRestaurant :many
SELECT d.id,
       d.name,
       d.description,
       d.price,
       d.restaurant_id,
       r.name                      as restaurant,
       r.username                  as restaurant_username,
       r.address,
       r.lat,
       r.lng,
       d.cuisine_id,
       c.name                      as cuisine,
       d.created_at,
       d.updated_at,
       coalesce(avg(rv.rating), 0) as rating,
       mc.id as category_id,
       mc.name as category_name
FROM dishes d
         LEFT JOIN restaurants r ON r.id = d.restaurant_id
         LEFT JOIN cuisines c ON c.id = d.cuisine_id
         LEFT JOIN reviews rv on rv.dish_id = d.id
         LEFT JOIN menu_categories mc on d.category_id = mc.id
WHERE d.restaurant_id = $1
GROUP BY d.id, d.name, d.description, d.price, d.restaurant_id, r.name, r.address,
         r.lat, r.lng, d.cuisine_id, c.name, r.username,
         d.created_at, d.updated_at, mc.id, mc.name
ORDER BY d.category_id, d.name
`

type GetDishesByRestaurantRow struct {
	ID                 int32              `json:"id"`
	Name               string             `json:"name"`
	Description        *string            `json:"description"`
	Price              int64              `json:"price"`
	RestaurantID       int32              `json:"restaurantId"`
	Restaurant         *string            `json:"restaurant"`
	RestaurantUsername *string            `json:"restaurantUsername"`
	Address            *string            `json:"address"`
	Lat                *float64           `json:"lat"`
	Lng                *float64           `json:"lng"`
	CuisineID          int16              `json:"cuisineId"`
	Cuisine            *string            `json:"cuisine"`
	CreatedAt          pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt          pgtype.Timestamptz `json:"updatedAt"`
	Rating             interface{}        `json:"rating"`
	CategoryID         *int32             `json:"categoryId"`
	CategoryName       *string            `json:"categoryName"`
}

func (q *Queries) GetDishesByRestaurant(ctx context.Context, db DBTX, restaurantID int32) ([]*GetDishesByRestaurantRow, error) {
	rows, err := db.Query(ctx, getDishesByRestaurant, restaurantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GetDishesByRestaurantRow{}
	for rows.Next() {
		var i GetDishesByRestaurantRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Price,
			&i.RestaurantID,
			&i.Restaurant,
			&i.RestaurantUsername,
			&i.Address,
			&i.Lat,
			&i.Lng,
			&i.CuisineID,
			&i.Cuisine,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Rating,
			&i.CategoryID,
			&i.CategoryName,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMenuCategoriesByRestaurantId = `-- name: GetMenuCategoriesByRestaurantId :many
SELECT mc.id, mc.name, mc.restaurant_id, mc.created_at, mc.updated_at
FROM menu_categories mc
WHERE mc.restaurant_id = $1
ORDER BY mc.name
`

func (q *Queries) GetMenuCategoriesByRestaurantId(ctx context.Context, db DBTX, restaurantID int32) ([]*MenuCategory, error) {
	rows, err := db.Query(ctx, getMenuCategoriesByRestaurantId, restaurantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*MenuCategory{}
	for rows.Next() {
		var i MenuCategory
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.RestaurantID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMenuCategoryById = `-- name: GetMenuCategoryById :one
SELECT mc.id, mc.name, mc.restaurant_id, mc.created_at, mc.updated_at
FROM menu_categories mc
WHERE mc.id = $1
`

func (q *Queries) GetMenuCategoryById(ctx context.Context, db DBTX, id int32) (*MenuCategory, error) {
	row := db.QueryRow(ctx, getMenuCategoryById, id)
	var i MenuCategory
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.RestaurantID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const updateDish = `-- name: UpdateDish :one
UPDATE dishes
SET name = coalesce($1, name),
    description = coalesce($2, description),
    price = coalesce($3, price),
    cuisine_id = coalesce($4, cuisine_id),
    category_id = $5,
    updated_at = now()
WHERE id = $6
RETURNING id, name, description, price, restaurant_id, cuisine_id, category_id, created_at, updated_at
`

type UpdateDishParams struct {
	Name        *string `json:"name"`
	Description *string `json:"description"`
	Price       *int64  `json:"price"`
	CuisineID   *int16  `json:"cuisineId"`
	CategoryID  *int32  `json:"categoryId"`
	DishID      int32   `json:"dishId"`
}

type UpdateDishRow struct {
	ID           int32              `json:"id"`
	Name         string             `json:"name"`
	Description  *string            `json:"description"`
	Price        int64              `json:"price"`
	RestaurantID int32              `json:"restaurantId"`
	CuisineID    int16              `json:"cuisineId"`
	CategoryID   *int32             `json:"categoryId"`
	CreatedAt    pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt    pgtype.Timestamptz `json:"updatedAt"`
}

func (q *Queries) UpdateDish(ctx context.Context, db DBTX, arg *UpdateDishParams) (*UpdateDishRow, error) {
	row := db.QueryRow(ctx, updateDish,
		arg.Name,
		arg.Description,
		arg.Price,
		arg.CuisineID,
		arg.CategoryID,
		arg.DishID,
	)
	var i UpdateDishRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.RestaurantID,
		&i.CuisineID,
		&i.CategoryID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
