// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Cuisine struct {
	ID        int16              `json:"id"`
	Name      string             `json:"name"`
	ParentID  *int16             `json:"parentId"`
	ImageUrl  *string            `json:"imageUrl"`
	CreatedAt pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt pgtype.Timestamptz `json:"updatedAt"`
}

type Dish struct {
	ID           int32              `json:"id"`
	Name         string             `json:"name"`
	Description  *string            `json:"description"`
	Price        int64              `json:"price"`
	CuisineID    int16              `json:"cuisineId"`
	RestaurantID int32              `json:"restaurantId"`
	CreatedAt    pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt    pgtype.Timestamptz `json:"updatedAt"`
}

type Post struct {
	ID           int64              `json:"id"`
	Caption      *string            `json:"caption"`
	CreatedAt    pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt    pgtype.Timestamptz `json:"updatedAt"`
	EditSnapshot []byte             `json:"editSnapshot"`
	Media        []byte             `json:"media"`
	RestaurantID *int32             `json:"restaurantId"`
}

type PostLike struct {
	PostID    int64              `json:"postId"`
	UserID    interface{}        `json:"userId"`
	CreatedAt pgtype.Timestamptz `json:"createdAt"`
}

type PostsComment struct {
	ID        int64       `json:"id"`
	PostID    int64       `json:"postId"`
	UserID    interface{} `json:"userId"`
	ReplyToID *int64      `json:"replyToId"`
	Content   *string     `json:"content"`
	Media     []byte      `json:"media"`
}

type Restaurant struct {
	ID          int32              `json:"id"`
	Name        string             `json:"name"`
	Description *string            `json:"description"`
	AvatarUrl   *string            `json:"avatarUrl"`
	Username    string             `json:"username"`
	Email       *string            `json:"email"`
	Phone       *string            `json:"phone"`
	Address     *string            `json:"address"`
	Lat         *float64           `json:"lat"`
	Lng         *float64           `json:"lng"`
	Document    []byte             `json:"document"`
	CreatedAt   pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt   pgtype.Timestamptz `json:"updatedAt"`
	IsApproved  *bool              `json:"isApproved"`
}

type RestaurantManager struct {
	UserID       interface{}        `json:"userId"`
	RestaurantID int32              `json:"restaurantId"`
	IsOwner      *bool              `json:"isOwner"`
	CreatedAt    pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt    pgtype.Timestamptz `json:"updatedAt"`
}

type Review struct {
	ID        int64              `json:"id"`
	Rating    int16              `json:"rating"`
	Comment   string             `json:"comment"`
	CreatedAt pgtype.Timestamptz `json:"createdAt"`
	UserID    interface{}        `json:"userId"`
	DishID    int32              `json:"dishId"`
	UpdatedAt pgtype.Timestamptz `json:"updatedAt"`
}

type User struct {
	ID          interface{}        `json:"id"`
	Username    string             `json:"username"`
	Email       string             `json:"email"`
	DisplayName string             `json:"displayName"`
	AvatarUrl   *string            `json:"avatarUrl"`
	Lat         *float64           `json:"lat"`
	Lng         *float64           `json:"lng"`
	Budget      *int64             `json:"budget"`
	CreatedAt   pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt   pgtype.Timestamptz `json:"updatedAt"`
}

type UserCuisine struct {
	UserID    interface{}        `json:"userId"`
	CuisineID int16              `json:"cuisineId"`
	CreatedAt pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt pgtype.Timestamptz `json:"updatedAt"`
}

type UserInteraction struct {
	ID               int32              `json:"id"`
	UserID           interface{}        `json:"userId"`
	DishID           int32              `json:"dishId"`
	InteractionScore *int16             `json:"interactionScore"`
	CreatedAt        pgtype.Timestamptz `json:"createdAt"`
}

type UserRecommendation struct {
	ID        int64              `json:"id"`
	UserID    interface{}        `json:"userId"`
	DishID    int32              `json:"dishId"`
	Score     float64            `json:"score"`
	CreatedAt pgtype.Timestamptz `json:"createdAt"`
}
