// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: posts.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkPostLike = `-- name: CheckPostLike :one
SELECT EXISTS(
    SELECT 1 FROM post_like
    WHERE post_id = $1 AND user_id = $2
)
`

type CheckPostLikeParams struct {
	PostID int64  `json:"postId"`
	UserID string `json:"userId"`
}

func (q *Queries) CheckPostLike(ctx context.Context, db DBTX, arg *CheckPostLikeParams) (bool, error) {
	row := db.QueryRow(ctx, checkPostLike, arg.PostID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createComment = `-- name: CreateComment :one
INSERT INTO posts_comment (post_id, user_id, reply_to_id, content, media)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, post_id, user_id, reply_to_id, content, media
`

type CreateCommentParams struct {
	PostID    int64   `json:"postId"`
	UserID    string  `json:"userId"`
	ReplyToID *int64  `json:"replyToId"`
	Content   *string `json:"content"`
	Media     []byte  `json:"media"`
}

func (q *Queries) CreateComment(ctx context.Context, db DBTX, arg *CreateCommentParams) (*PostsComment, error) {
	row := db.QueryRow(ctx, createComment,
		arg.PostID,
		arg.UserID,
		arg.ReplyToID,
		arg.Content,
		arg.Media,
	)
	var i PostsComment
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.UserID,
		&i.ReplyToID,
		&i.Content,
		&i.Media,
	)
	return &i, err
}

const createPost = `-- name: CreatePost :one
INSERT INTO posts (caption, media, restaurant_id)
VALUES ($1, $2, $3)
RETURNING id, caption, created_at, updated_at, edit_snapshot, media, restaurant_id
`

type CreatePostParams struct {
	Caption      *string `json:"caption"`
	Media        []byte  `json:"media"`
	RestaurantID *int32  `json:"restaurantId"`
}

func (q *Queries) CreatePost(ctx context.Context, db DBTX, arg *CreatePostParams) (*Post, error) {
	row := db.QueryRow(ctx, createPost, arg.Caption, arg.Media, arg.RestaurantID)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.Caption,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EditSnapshot,
		&i.Media,
		&i.RestaurantID,
	)
	return &i, err
}

const deleteComment = `-- name: DeleteComment :exec
DELETE FROM posts_comment WHERE id = $1 AND user_id = $2
`

type DeleteCommentParams struct {
	ID     int32  `json:"id"`
	UserID string `json:"userId"`
}

func (q *Queries) DeleteComment(ctx context.Context, db DBTX, arg *DeleteCommentParams) error {
	_, err := db.Exec(ctx, deleteComment, arg.ID, arg.UserID)
	return err
}

const deletePost = `-- name: DeletePost :exec
DELETE FROM posts WHERE id = $1
`

func (q *Queries) DeletePost(ctx context.Context, db DBTX, id int32) error {
	_, err := db.Exec(ctx, deletePost, id)
	return err
}

const getCommentByID = `-- name: GetCommentByID :one
SELECT
    pc.id,
    pc.post_id,
    pc.user_id,
    pc.reply_to_id,
    pc.content,
    pc.media,
    u.username,
    u.display_name,
    u.avatar_url
FROM posts_comment pc
JOIN users u ON pc.user_id = u.id
WHERE pc.id = $1
`

type GetCommentByIDRow struct {
	ID          int32   `json:"id"`
	PostID      int64   `json:"postId"`
	UserID      string  `json:"userId"`
	ReplyToID   *int64  `json:"replyToId"`
	Content     *string `json:"content"`
	Media       []byte  `json:"media"`
	Username    string  `json:"username"`
	DisplayName string  `json:"displayName"`
	AvatarUrl   *string `json:"avatarUrl"`
}

func (q *Queries) GetCommentByID(ctx context.Context, db DBTX, id int32) (*GetCommentByIDRow, error) {
	row := db.QueryRow(ctx, getCommentByID, id)
	var i GetCommentByIDRow
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.UserID,
		&i.ReplyToID,
		&i.Content,
		&i.Media,
		&i.Username,
		&i.DisplayName,
		&i.AvatarUrl,
	)
	return &i, err
}

const getCommentsByPost = `-- name: GetCommentsByPost :many
SELECT
    pc.id,
    pc.post_id,
    pc.user_id,
    pc.reply_to_id,
    pc.content,
    pc.media,
    u.username,
    u.display_name,
    u.avatar_url
FROM posts_comment pc
JOIN users u ON pc.user_id = u.id
WHERE pc.post_id = $1
ORDER BY pc.id ASC
`

type GetCommentsByPostRow struct {
	ID          int32   `json:"id"`
	PostID      int64   `json:"postId"`
	UserID      string  `json:"userId"`
	ReplyToID   *int64  `json:"replyToId"`
	Content     *string `json:"content"`
	Media       []byte  `json:"media"`
	Username    string  `json:"username"`
	DisplayName string  `json:"displayName"`
	AvatarUrl   *string `json:"avatarUrl"`
}

func (q *Queries) GetCommentsByPost(ctx context.Context, db DBTX, postID int64) ([]*GetCommentsByPostRow, error) {
	rows, err := db.Query(ctx, getCommentsByPost, postID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GetCommentsByPostRow{}
	for rows.Next() {
		var i GetCommentsByPostRow
		if err := rows.Scan(
			&i.ID,
			&i.PostID,
			&i.UserID,
			&i.ReplyToID,
			&i.Content,
			&i.Media,
			&i.Username,
			&i.DisplayName,
			&i.AvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPostByID = `-- name: GetPostByID :one
SELECT
    p.id,
    p.caption,
    p.media,
    p.created_at,
    p.updated_at,
    p.restaurant_id,
    r.name as restaurant_name,
    r.username as restaurant_username,
    r.avatar_url as restaurant_avatar,
    COUNT(DISTINCT pl.user_id) as like_count
FROM posts p
JOIN restaurants r ON p.restaurant_id = r.id
LEFT JOIN post_like pl ON p.id = pl.post_id
WHERE p.id = $1
GROUP BY p.id, p.caption, p.media, p.created_at, p.updated_at, p.restaurant_id, r.name, r.username, r.avatar_url
`

type GetPostByIDRow struct {
	ID                 int32              `json:"id"`
	Caption            *string            `json:"caption"`
	Media              []byte             `json:"media"`
	CreatedAt          pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt          pgtype.Timestamptz `json:"updatedAt"`
	RestaurantID       *int32             `json:"restaurantId"`
	RestaurantName     string             `json:"restaurantName"`
	RestaurantUsername string             `json:"restaurantUsername"`
	RestaurantAvatar   *string            `json:"restaurantAvatar"`
	LikeCount          int64              `json:"likeCount"`
}

func (q *Queries) GetPostByID(ctx context.Context, db DBTX, id int32) (*GetPostByIDRow, error) {
	row := db.QueryRow(ctx, getPostByID, id)
	var i GetPostByIDRow
	err := row.Scan(
		&i.ID,
		&i.Caption,
		&i.Media,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RestaurantID,
		&i.RestaurantName,
		&i.RestaurantUsername,
		&i.RestaurantAvatar,
		&i.LikeCount,
	)
	return &i, err
}

const getPosts = `-- name: GetPosts :many
SELECT
    p.id,
    p.caption,
    p.media::text[] as media,
    p.created_at,
    p.updated_at,
    p.restaurant_id,
    r.name as restaurant_name,
    r.username as restaurant_username,
    r.avatar_url as restaurant_avatar,
    COUNT(DISTINCT pl.user_id) as like_count
FROM posts p
JOIN restaurants r ON p.restaurant_id = r.id
LEFT JOIN post_like pl ON p.id = pl.post_id
WHERE ($3::varchar(64) = '' or r.id::text = $3 or r.username = $3)
GROUP BY p.id, p.caption, p.media, p.created_at, p.updated_at, p.restaurant_id, r.name, r.username, r.avatar_url
ORDER BY p.created_at DESC
LIMIT $1 OFFSET $2
`

type GetPostsParams struct {
	Limit        int32  `json:"limit"`
	Offset       int32  `json:"offset"`
	RestaurantID string `json:"restaurantId"`
}

type GetPostsRow struct {
	ID                 int32              `json:"id"`
	Caption            *string            `json:"caption"`
	Media              []string           `json:"media"`
	CreatedAt          pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt          pgtype.Timestamptz `json:"updatedAt"`
	RestaurantID       *int32             `json:"restaurantId"`
	RestaurantName     string             `json:"restaurantName"`
	RestaurantUsername string             `json:"restaurantUsername"`
	RestaurantAvatar   *string            `json:"restaurantAvatar"`
	LikeCount          int64              `json:"likeCount"`
}

func (q *Queries) GetPosts(ctx context.Context, db DBTX, arg *GetPostsParams) ([]*GetPostsRow, error) {
	rows, err := db.Query(ctx, getPosts, arg.Limit, arg.Offset, arg.RestaurantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GetPostsRow{}
	for rows.Next() {
		var i GetPostsRow
		if err := rows.Scan(
			&i.ID,
			&i.Caption,
			&i.Media,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RestaurantID,
			&i.RestaurantName,
			&i.RestaurantUsername,
			&i.RestaurantAvatar,
			&i.LikeCount,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPostsByRestaurant = `-- name: GetPostsByRestaurant :many
SELECT
    p.id,
    p.caption,
    p.media,
    p.created_at,
    p.updated_at,
    p.restaurant_id,
    r.name as restaurant_name,
    r.username as restaurant_username,
    r.avatar_url as restaurant_avatar,
    COUNT(DISTINCT pl.user_id) as like_count
FROM posts p
JOIN restaurants r ON p.restaurant_id = r.id
LEFT JOIN post_like pl ON p.id = pl.post_id
WHERE p.restaurant_id = $1
GROUP BY p.id, p.caption, p.media, p.created_at, p.updated_at, p.restaurant_id, r.name, r.username, r.avatar_url
ORDER BY p.created_at DESC
LIMIT $2 OFFSET $3
`

type GetPostsByRestaurantParams struct {
	RestaurantID *int32 `json:"restaurantId"`
	Limit        int32  `json:"limit"`
	Offset       int32  `json:"offset"`
}

type GetPostsByRestaurantRow struct {
	ID                 int32              `json:"id"`
	Caption            *string            `json:"caption"`
	Media              []byte             `json:"media"`
	CreatedAt          pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt          pgtype.Timestamptz `json:"updatedAt"`
	RestaurantID       *int32             `json:"restaurantId"`
	RestaurantName     string             `json:"restaurantName"`
	RestaurantUsername string             `json:"restaurantUsername"`
	RestaurantAvatar   *string            `json:"restaurantAvatar"`
	LikeCount          int64              `json:"likeCount"`
}

func (q *Queries) GetPostsByRestaurant(ctx context.Context, db DBTX, arg *GetPostsByRestaurantParams) ([]*GetPostsByRestaurantRow, error) {
	rows, err := db.Query(ctx, getPostsByRestaurant, arg.RestaurantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GetPostsByRestaurantRow{}
	for rows.Next() {
		var i GetPostsByRestaurantRow
		if err := rows.Scan(
			&i.ID,
			&i.Caption,
			&i.Media,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RestaurantID,
			&i.RestaurantName,
			&i.RestaurantUsername,
			&i.RestaurantAvatar,
			&i.LikeCount,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const likePost = `-- name: LikePost :exec
INSERT INTO post_like (post_id, user_id)
VALUES ($1, $2)
ON CONFLICT (post_id, user_id) DO NOTHING
`

type LikePostParams struct {
	PostID int64  `json:"postId"`
	UserID string `json:"userId"`
}

func (q *Queries) LikePost(ctx context.Context, db DBTX, arg *LikePostParams) error {
	_, err := db.Exec(ctx, likePost, arg.PostID, arg.UserID)
	return err
}

const unlikePost = `-- name: UnlikePost :exec
DELETE FROM post_like
WHERE post_id = $1 AND user_id = $2
`

type UnlikePostParams struct {
	PostID int64  `json:"postId"`
	UserID string `json:"userId"`
}

func (q *Queries) UnlikePost(ctx context.Context, db DBTX, arg *UnlikePostParams) error {
	_, err := db.Exec(ctx, unlikePost, arg.PostID, arg.UserID)
	return err
}

const updatePost = `-- name: UpdatePost :one
UPDATE posts
SET
    caption = coalesce($1, caption),
    media = coalesce($2, media),
    updated_at = now()
WHERE id = $3
RETURNING id, caption, created_at, updated_at, edit_snapshot, media, restaurant_id
`

type UpdatePostParams struct {
	Caption *string `json:"caption"`
	Media   []byte  `json:"media"`
	PostID  int32   `json:"postId"`
}

func (q *Queries) UpdatePost(ctx context.Context, db DBTX, arg *UpdatePostParams) (*Post, error) {
	row := db.QueryRow(ctx, updatePost, arg.Caption, arg.Media, arg.PostID)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.Caption,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EditSnapshot,
		&i.Media,
		&i.RestaurantID,
	)
	return &i, err
}
