// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: recommendations.sql

package database

import (
	"context"
)

const getTopRatedDishes = `-- name: GetTopRatedDishes :many
SELECT
    d.id,
    d.name,
    d.description,
    d.price,
    d.restaurant_id,
    r.name as restaurant_name,
    r.username as restaurant_username,
    d.cuisine_id,
    c.name as cuisine_name,
    COALESCE(AVG(rev.rating), 0) as average_rating,
    COUNT(rev.id) as review_count
FROM dishes d
JOIN restaurants r ON d.restaurant_id = r.id
LEFT JOIN cuisines c ON d.cuisine_id = c.id
LEFT JOIN reviews rev ON d.id = rev.dish_id
WHERE r.is_approved = true
GROUP BY d.id, d.name, d.description, d.price, d.restaurant_id, r.name, r.username, d.cuisine_id, c.name
HAVING COUNT(rev.id) > 0
ORDER BY average_rating DESC, review_count DESC
LIMIT $1
`

type GetTopRatedDishesRow struct {
	ID                 int32       `json:"id"`
	Name               string      `json:"name"`
	Description        *string     `json:"description"`
	Price              int64       `json:"price"`
	RestaurantID       int32       `json:"restaurantId"`
	RestaurantName     string      `json:"restaurantName"`
	RestaurantUsername string      `json:"restaurantUsername"`
	CuisineID          int16       `json:"cuisineId"`
	CuisineName        *string     `json:"cuisineName"`
	AverageRating      interface{} `json:"averageRating"`
	ReviewCount        int64       `json:"reviewCount"`
}

func (q *Queries) GetTopRatedDishes(ctx context.Context, db DBTX, limit int32) ([]*GetTopRatedDishesRow, error) {
	rows, err := db.Query(ctx, getTopRatedDishes, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GetTopRatedDishesRow{}
	for rows.Next() {
		var i GetTopRatedDishesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Price,
			&i.RestaurantID,
			&i.RestaurantName,
			&i.RestaurantUsername,
			&i.CuisineID,
			&i.CuisineName,
			&i.AverageRating,
			&i.ReviewCount,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
