// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: restaurants.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const approveRestaurantProfile = `-- name: ApproveRestaurantProfile :exec
UPDATE restaurants
SET is_approved = $1
WHERE id = $2
RETURNING id, name, description, avatar_url, username, email, phone, address, lat, lng, document, created_at, updated_at, is_approved
`

type ApproveRestaurantProfileParams struct {
	IsApproved *bool `json:"isApproved"`
	ID         int32 `json:"id"`
}

func (q *Queries) ApproveRestaurantProfile(ctx context.Context, db DBTX, arg *ApproveRestaurantProfileParams) error {
	_, err := db.Exec(ctx, approveRestaurantProfile, arg.IsApproved, arg.ID)
	return err
}

const createRestaurant = `-- name: CreateRestaurant :one
INSERT INTO restaurants (name, description, avatar_url, username, email, phone, address, lat, lng, document)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, name, description, avatar_url, username, email, phone, address, lat, lng, document, created_at, updated_at, is_approved
`

type CreateRestaurantParams struct {
	Name        string   `json:"name"`
	Description *string  `json:"description"`
	AvatarUrl   *string  `json:"avatarUrl"`
	Username    string   `json:"username"`
	Email       *string  `json:"email"`
	Phone       *string  `json:"phone"`
	Address     *string  `json:"address"`
	Lat         *float64 `json:"lat"`
	Lng         *float64 `json:"lng"`
	Document    []byte   `json:"document"`
}

func (q *Queries) CreateRestaurant(ctx context.Context, db DBTX, arg *CreateRestaurantParams) (*Restaurant, error) {
	row := db.QueryRow(ctx, createRestaurant,
		arg.Name,
		arg.Description,
		arg.AvatarUrl,
		arg.Username,
		arg.Email,
		arg.Phone,
		arg.Address,
		arg.Lat,
		arg.Lng,
		arg.Document,
	)
	var i Restaurant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.AvatarUrl,
		&i.Username,
		&i.Email,
		&i.Phone,
		&i.Address,
		&i.Lat,
		&i.Lng,
		&i.Document,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsApproved,
	)
	return &i, err
}

const deleteRestaurant = `-- name: DeleteRestaurant :exec
DELETE FROM restaurants WHERE id = $1
`

func (q *Queries) DeleteRestaurant(ctx context.Context, db DBTX, id int32) error {
	_, err := db.Exec(ctx, deleteRestaurant, id)
	return err
}

const getRestaurantByID = `-- name: GetRestaurantByID :one
SELECT
    r.id,
    r.name,
    r.description,
    r.avatar_url,
    r.username,
    r.email,
    r.phone,
    r.address,
    r.lat,
    r.lng,
    r.created_at,
    r.updated_at
FROM restaurants r
WHERE id = $1
`

type GetRestaurantByIDRow struct {
	ID          int32              `json:"id"`
	Name        string             `json:"name"`
	Description *string            `json:"description"`
	AvatarUrl   *string            `json:"avatarUrl"`
	Username    string             `json:"username"`
	Email       *string            `json:"email"`
	Phone       *string            `json:"phone"`
	Address     *string            `json:"address"`
	Lat         *float64           `json:"lat"`
	Lng         *float64           `json:"lng"`
	CreatedAt   pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt   pgtype.Timestamptz `json:"updatedAt"`
}

func (q *Queries) GetRestaurantByID(ctx context.Context, db DBTX, id int32) (*GetRestaurantByIDRow, error) {
	row := db.QueryRow(ctx, getRestaurantByID, id)
	var i GetRestaurantByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.AvatarUrl,
		&i.Username,
		&i.Email,
		&i.Phone,
		&i.Address,
		&i.Lat,
		&i.Lng,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getRestaurants = `-- name: GetRestaurants :many
SELECT
    r.id,
    r.name,
    r.description,
    r.avatar_url,
    r.username,
    r.email,
    r.phone,
    r.address,
    r.lat,
    r.lng,
    r.created_at,
    r.updated_at,
    r.is_approved
FROM restaurants r
LIMIT $1 OFFSET $2
`

type GetRestaurantsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type GetRestaurantsRow struct {
	ID          int32              `json:"id"`
	Name        string             `json:"name"`
	Description *string            `json:"description"`
	AvatarUrl   *string            `json:"avatarUrl"`
	Username    string             `json:"username"`
	Email       *string            `json:"email"`
	Phone       *string            `json:"phone"`
	Address     *string            `json:"address"`
	Lat         *float64           `json:"lat"`
	Lng         *float64           `json:"lng"`
	CreatedAt   pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt   pgtype.Timestamptz `json:"updatedAt"`
	IsApproved  *bool              `json:"isApproved"`
}

func (q *Queries) GetRestaurants(ctx context.Context, db DBTX, arg *GetRestaurantsParams) ([]*GetRestaurantsRow, error) {
	rows, err := db.Query(ctx, getRestaurants, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GetRestaurantsRow{}
	for rows.Next() {
		var i GetRestaurantsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.AvatarUrl,
			&i.Username,
			&i.Email,
			&i.Phone,
			&i.Address,
			&i.Lat,
			&i.Lng,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsApproved,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRestaurant = `-- name: UpdateRestaurant :exec
UPDATE restaurants
SET
    name = coalesce($1, name),
    description = coalesce($2, description),
    avatar_url = coalesce($3, avatar_url),
    username = coalesce($4, username),
    email = coalesce($5, email),
    phone = coalesce(sqlc('phone'), phone),
    address = coalesce($6, address),
    lat = coalesce($7, lat),
    lng = coalesce($8, lng),
    updated_at = now()
WHERE id = $9
RETURNING id, name, description, avatar_url, username, email, phone, address, lat, lng, document, created_at, updated_at, is_approved
`

type UpdateRestaurantParams struct {
	Name         *string  `json:"name"`
	Description  *string  `json:"description"`
	AvatarUrl    *string  `json:"avatarUrl"`
	Username     *string  `json:"username"`
	Email        *string  `json:"email"`
	Address      *string  `json:"address"`
	Lat          *float64 `json:"lat"`
	Lng          *float64 `json:"lng"`
	RestaurantID int32    `json:"restaurantId"`
}

func (q *Queries) UpdateRestaurant(ctx context.Context, db DBTX, arg *UpdateRestaurantParams) error {
	_, err := db.Exec(ctx, updateRestaurant,
		arg.Name,
		arg.Description,
		arg.AvatarUrl,
		arg.Username,
		arg.Email,
		arg.Address,
		arg.Lat,
		arg.Lng,
		arg.RestaurantID,
	)
	return err
}
