// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: restaurants.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addRestaurantManager = `-- name: AddRestaurantManager :exec
INSERT INTO restaurant_manager (restaurant_id, user_id, is_owner)
VALUES ($1::int, $2::varchar(64), $3::bool)
`

type AddRestaurantManagerParams struct {
	RestaurantID int32  `json:"restaurantId"`
	UserID       string `json:"userId"`
	IsOwner      bool   `json:"isOwner"`
}

func (q *Queries) AddRestaurantManager(ctx context.Context, db DBTX, arg *AddRestaurantManagerParams) error {
	_, err := db.Exec(ctx, addRestaurantManager, arg.RestaurantID, arg.UserID, arg.IsOwner)
	return err
}

const createRestaurant = `-- name: CreateRestaurant :one
INSERT INTO restaurants (name, description, avatar_url, username, email, phone, address, lat, lng, document)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10) RETURNING id, name, description, avatar_url, username, email, phone, address, lat, lng, document, created_at, updated_at, is_approved, open_hour, website, cover_url
`

type CreateRestaurantParams struct {
	Name        string   `json:"name"`
	Description *string  `json:"description"`
	AvatarUrl   *string  `json:"avatarUrl"`
	Username    string   `json:"username"`
	Email       *string  `json:"email"`
	Phone       *string  `json:"phone"`
	Address     *string  `json:"address"`
	Lat         *float64 `json:"lat"`
	Lng         *float64 `json:"lng"`
	Document    []byte   `json:"document"`
}

func (q *Queries) CreateRestaurant(ctx context.Context, db DBTX, arg *CreateRestaurantParams) (*Restaurant, error) {
	row := db.QueryRow(ctx, createRestaurant,
		arg.Name,
		arg.Description,
		arg.AvatarUrl,
		arg.Username,
		arg.Email,
		arg.Phone,
		arg.Address,
		arg.Lat,
		arg.Lng,
		arg.Document,
	)
	var i Restaurant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.AvatarUrl,
		&i.Username,
		&i.Email,
		&i.Phone,
		&i.Address,
		&i.Lat,
		&i.Lng,
		&i.Document,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsApproved,
		&i.OpenHour,
		&i.Website,
		&i.CoverUrl,
	)
	return &i, err
}

const deleteRestaurant = `-- name: DeleteRestaurant :exec
DELETE
FROM restaurants
WHERE id = $1
`

func (q *Queries) DeleteRestaurant(ctx context.Context, db DBTX, id int32) error {
	_, err := db.Exec(ctx, deleteRestaurant, id)
	return err
}

const getManagingRestaurantByUser = `-- name: GetManagingRestaurantByUser :many
SELECT r.id, r.name, r.description, r.avatar_url, r.username, r.email, r.phone, r.address, r.lat, r.lng, r.document, r.created_at, r.updated_at, r.is_approved, r.open_hour, r.website, r.cover_url, rm.is_owner
FROM restaurant_manager rm
         JOIN restaurants r ON rm.restaurant_id = r.id
WHERE rm.user_id = $1
`

type GetManagingRestaurantByUserRow struct {
	ID          int32              `json:"id"`
	Name        string             `json:"name"`
	Description *string            `json:"description"`
	AvatarUrl   *string            `json:"avatarUrl"`
	Username    string             `json:"username"`
	Email       *string            `json:"email"`
	Phone       *string            `json:"phone"`
	Address     *string            `json:"address"`
	Lat         *float64           `json:"lat"`
	Lng         *float64           `json:"lng"`
	Document    []byte             `json:"document"`
	CreatedAt   pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt   pgtype.Timestamptz `json:"updatedAt"`
	IsApproved  *bool              `json:"isApproved"`
	OpenHour    *string            `json:"openHour"`
	Website     *string            `json:"website"`
	CoverUrl    *string            `json:"coverUrl"`
	IsOwner     *bool              `json:"isOwner"`
}

func (q *Queries) GetManagingRestaurantByUser(ctx context.Context, db DBTX, userID string) ([]*GetManagingRestaurantByUserRow, error) {
	rows, err := db.Query(ctx, getManagingRestaurantByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GetManagingRestaurantByUserRow{}
	for rows.Next() {
		var i GetManagingRestaurantByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.AvatarUrl,
			&i.Username,
			&i.Email,
			&i.Phone,
			&i.Address,
			&i.Lat,
			&i.Lng,
			&i.Document,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsApproved,
			&i.OpenHour,
			&i.Website,
			&i.CoverUrl,
			&i.IsOwner,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRestaurantByOwnerId = `-- name: GetRestaurantByOwnerId :one
SELECT r.id,
       r.name,
       r.description,
       r.avatar_url,
       r.username,
       r.email,
       r.phone,
       r.address,
       r.lat,
       r.lng,
       r.created_at,
       r.updated_at,
       r.is_approved
FROM restaurants r
         JOIN restaurant_manager rm ON r.id = rm.restaurant_id
WHERE rm.user_id = $1
  AND rm.is_owner = true LIMIT 1
`

type GetRestaurantByOwnerIdRow struct {
	ID          int32              `json:"id"`
	Name        string             `json:"name"`
	Description *string            `json:"description"`
	AvatarUrl   *string            `json:"avatarUrl"`
	Username    string             `json:"username"`
	Email       *string            `json:"email"`
	Phone       *string            `json:"phone"`
	Address     *string            `json:"address"`
	Lat         *float64           `json:"lat"`
	Lng         *float64           `json:"lng"`
	CreatedAt   pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt   pgtype.Timestamptz `json:"updatedAt"`
	IsApproved  *bool              `json:"isApproved"`
}

func (q *Queries) GetRestaurantByOwnerId(ctx context.Context, db DBTX, userID string) (*GetRestaurantByOwnerIdRow, error) {
	row := db.QueryRow(ctx, getRestaurantByOwnerId, userID)
	var i GetRestaurantByOwnerIdRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.AvatarUrl,
		&i.Username,
		&i.Email,
		&i.Phone,
		&i.Address,
		&i.Lat,
		&i.Lng,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsApproved,
	)
	return &i, err
}

const getRestaurantByUsername = `-- name: GetRestaurantByUsername :one
SELECT r.id,
       r.name,
       r.description,
       r.avatar_url,
       r.username,
       r.email,
       r.phone,
       r.address,
       r.lat,
       r.lng,
       r.created_at,
       r.updated_at,
       r.is_approved
FROM restaurants r
WHERE r.username = $1
`

type GetRestaurantByUsernameRow struct {
	ID          int32              `json:"id"`
	Name        string             `json:"name"`
	Description *string            `json:"description"`
	AvatarUrl   *string            `json:"avatarUrl"`
	Username    string             `json:"username"`
	Email       *string            `json:"email"`
	Phone       *string            `json:"phone"`
	Address     *string            `json:"address"`
	Lat         *float64           `json:"lat"`
	Lng         *float64           `json:"lng"`
	CreatedAt   pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt   pgtype.Timestamptz `json:"updatedAt"`
	IsApproved  *bool              `json:"isApproved"`
}

func (q *Queries) GetRestaurantByUsername(ctx context.Context, db DBTX, username string) (*GetRestaurantByUsernameRow, error) {
	row := db.QueryRow(ctx, getRestaurantByUsername, username)
	var i GetRestaurantByUsernameRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.AvatarUrl,
		&i.Username,
		&i.Email,
		&i.Phone,
		&i.Address,
		&i.Lat,
		&i.Lng,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsApproved,
	)
	return &i, err
}

const getRestaurantHighlights = `-- name: GetRestaurantHighlights :many
SELECT d.id,
       d.name,
       d.description,
       d.price,
       COALESCE(AVG(rev.rating), 0) as rating,
       COUNT(rev.id)                as review_count
FROM dishes d
         LEFT JOIN reviews rev ON d.id = rev.dish_id
WHERE d.restaurant_id = $1
GROUP BY d.id, d.name, d.description, d.price
ORDER BY rating DESC, review_count DESC LIMIT 6
`

type GetRestaurantHighlightsRow struct {
	ID          int32       `json:"id"`
	Name        string      `json:"name"`
	Description *string     `json:"description"`
	Price       int64       `json:"price"`
	Rating      interface{} `json:"rating"`
	ReviewCount int64       `json:"reviewCount"`
}

func (q *Queries) GetRestaurantHighlights(ctx context.Context, db DBTX, restaurantID int32) ([]*GetRestaurantHighlightsRow, error) {
	rows, err := db.Query(ctx, getRestaurantHighlights, restaurantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GetRestaurantHighlightsRow{}
	for rows.Next() {
		var i GetRestaurantHighlightsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Price,
			&i.Rating,
			&i.ReviewCount,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRestaurantManagers = `-- name: GetRestaurantManagers :many
SELECT u.id,
       u.username,
       u.display_name,
       u.email,
       u.avatar_url,
       rm.restaurant_id,
       rm.is_owner
FROM restaurant_manager rm
         JOIN users u ON rm.user_id = u.id
WHERE rm.restaurant_id = $1
`

type GetRestaurantManagersRow struct {
	ID           string  `json:"id"`
	Username     string  `json:"username"`
	DisplayName  string  `json:"displayName"`
	Email        string  `json:"email"`
	AvatarUrl    *string `json:"avatarUrl"`
	RestaurantID int32   `json:"restaurantId"`
	IsOwner      *bool   `json:"isOwner"`
}

func (q *Queries) GetRestaurantManagers(ctx context.Context, db DBTX, restaurantID int32) ([]*GetRestaurantManagersRow, error) {
	rows, err := db.Query(ctx, getRestaurantManagers, restaurantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GetRestaurantManagersRow{}
	for rows.Next() {
		var i GetRestaurantManagersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.DisplayName,
			&i.Email,
			&i.AvatarUrl,
			&i.RestaurantID,
			&i.IsOwner,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRestaurantProfile = `-- name: GetRestaurantProfile :one
SELECT r.id,
       r.name,
       r.description,
       r.avatar_url,
       r.username,
       r.email,
       r.phone,
       r.address,
       r.lat,
       r.lng,
       r.created_at,
       r.updated_at,
       r.is_approved,
       COUNT(DISTINCT d.id)         as dish_count,
       COUNT(DISTINCT rev.id)       as review_count,
       COALESCE(AVG(rev.rating), 0) as average_rating,
       COUNT(DISTINCT p.id)         as post_count
FROM restaurants r
         LEFT JOIN dishes d ON r.id = d.restaurant_id
         LEFT JOIN reviews rev ON d.id = rev.dish_id
         LEFT JOIN posts p ON r.id = p.restaurant_id
WHERE r.id = $1
GROUP BY r.id, r.name, r.description, r.avatar_url, r.username, r.email, r.phone, r.address, r.lat, r.lng, r.created_at,
         r.updated_at, r.is_approved
`

type GetRestaurantProfileRow struct {
	ID            int32              `json:"id"`
	Name          string             `json:"name"`
	Description   *string            `json:"description"`
	AvatarUrl     *string            `json:"avatarUrl"`
	Username      string             `json:"username"`
	Email         *string            `json:"email"`
	Phone         *string            `json:"phone"`
	Address       *string            `json:"address"`
	Lat           *float64           `json:"lat"`
	Lng           *float64           `json:"lng"`
	CreatedAt     pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt     pgtype.Timestamptz `json:"updatedAt"`
	IsApproved    *bool              `json:"isApproved"`
	DishCount     int64              `json:"dishCount"`
	ReviewCount   int64              `json:"reviewCount"`
	AverageRating interface{}        `json:"averageRating"`
	PostCount     int64              `json:"postCount"`
}

func (q *Queries) GetRestaurantProfile(ctx context.Context, db DBTX, id int32) (*GetRestaurantProfileRow, error) {
	row := db.QueryRow(ctx, getRestaurantProfile, id)
	var i GetRestaurantProfileRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.AvatarUrl,
		&i.Username,
		&i.Email,
		&i.Phone,
		&i.Address,
		&i.Lat,
		&i.Lng,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsApproved,
		&i.DishCount,
		&i.ReviewCount,
		&i.AverageRating,
		&i.PostCount,
	)
	return &i, err
}

const getRestaurantRecentReviews = `-- name: GetRestaurantRecentReviews :many
SELECT rev.id,
       rev.rating,
       rev.comment,
       rev.created_at,
       u.username,
       u.display_name,
       u.avatar_url,
       d.name as dish_name
FROM reviews rev
         JOIN users u ON rev.user_id = u.id
         JOIN dishes d ON rev.dish_id = d.id
WHERE d.restaurant_id = $1
ORDER BY rev.created_at DESC LIMIT 10
`

type GetRestaurantRecentReviewsRow struct {
	ID          int32              `json:"id"`
	Rating      int16              `json:"rating"`
	Comment     string             `json:"comment"`
	CreatedAt   pgtype.Timestamptz `json:"createdAt"`
	Username    string             `json:"username"`
	DisplayName string             `json:"displayName"`
	AvatarUrl   *string            `json:"avatarUrl"`
	DishName    string             `json:"dishName"`
}

func (q *Queries) GetRestaurantRecentReviews(ctx context.Context, db DBTX, restaurantID int32) ([]*GetRestaurantRecentReviewsRow, error) {
	rows, err := db.Query(ctx, getRestaurantRecentReviews, restaurantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GetRestaurantRecentReviewsRow{}
	for rows.Next() {
		var i GetRestaurantRecentReviewsRow
		if err := rows.Scan(
			&i.ID,
			&i.Rating,
			&i.Comment,
			&i.CreatedAt,
			&i.Username,
			&i.DisplayName,
			&i.AvatarUrl,
			&i.DishName,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRestaurants = `-- name: GetRestaurants :many
SELECT r.id,
       r.name,
       r.description,
       r.avatar_url,
       r.username,
       r.email,
       r.phone,
       r.address,
       r.open_hour,
       r.lat,
       r.lng,
       r.website,
       r.cover_url,
       r.created_at,
       r.updated_at,
       r.is_approved,
       coalesce(avg(rv.rating), 0) as average_rating,
       count(DISTINCT d.id) as dish_count,
       count(DISTINCT rv.id) as review_count,
       (SELECT count(*) FROM posts p where p.restaurant_id = r.id) as post_count,
       (SELECT count(*) FROM user_restaurant_follow urf2 WHERE urf2.restaurant_id = r.id) as follower_count
FROM restaurants r
         LEFT JOIN user_restaurant_follow urf on r.id = urf.restaurant_id
         LEFT JOIN restaurant_manager rm on rm.restaurant_id = r.id
         LEFT JOIN dishes d on d.restaurant_id = r.id
         LEFT JOIN reviews rv on rv.dish_id = d.id
WHERE ($3::varchar(64) = '' or urf.user_id = $3)
  AND ($4::varchar(64) = '' or rm.user_id = $4)
  AND ($5::varchar(64) = '' or r.id::text = $5 or r.username = $5)
GROUP BY r.id,
         r.name,
         r.description,
         r.avatar_url,
         r.username,
         r.email,
         r.phone,
         r.address,
         r.open_hour,
         r.lat,
         r.lng,
         r.website,
         r.cover_url,
         r.created_at,
         r.updated_at,
         r.is_approved,
         post_count,
         follower_count
LIMIT $1 OFFSET $2
`

type GetRestaurantsParams struct {
	Limit        int32  `json:"limit"`
	Offset       int32  `json:"offset"`
	FollowBy     string `json:"followBy"`
	ManagedBy    string `json:"managedBy"`
	RestaurantID string `json:"restaurantId"`
}

type GetRestaurantsRow struct {
	ID            int32              `json:"id"`
	Name          string             `json:"name"`
	Description   *string            `json:"description"`
	AvatarUrl     *string            `json:"avatarUrl"`
	Username      string             `json:"username"`
	Email         *string            `json:"email"`
	Phone         *string            `json:"phone"`
	Address       *string            `json:"address"`
	OpenHour      *string            `json:"openHour"`
	Lat           *float64           `json:"lat"`
	Lng           *float64           `json:"lng"`
	Website       *string            `json:"website"`
	CoverUrl      *string            `json:"coverUrl"`
	CreatedAt     pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt     pgtype.Timestamptz `json:"updatedAt"`
	IsApproved    *bool              `json:"isApproved"`
	AverageRating interface{}        `json:"averageRating"`
	DishCount     int64              `json:"dishCount"`
	ReviewCount   int64              `json:"reviewCount"`
	PostCount     int64              `json:"postCount"`
	FollowerCount int64              `json:"followerCount"`
}

func (q *Queries) GetRestaurants(ctx context.Context, db DBTX, arg *GetRestaurantsParams) ([]*GetRestaurantsRow, error) {
	rows, err := db.Query(ctx, getRestaurants,
		arg.Limit,
		arg.Offset,
		arg.FollowBy,
		arg.ManagedBy,
		arg.RestaurantID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GetRestaurantsRow{}
	for rows.Next() {
		var i GetRestaurantsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.AvatarUrl,
			&i.Username,
			&i.Email,
			&i.Phone,
			&i.Address,
			&i.OpenHour,
			&i.Lat,
			&i.Lng,
			&i.Website,
			&i.CoverUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsApproved,
			&i.AverageRating,
			&i.DishCount,
			&i.ReviewCount,
			&i.PostCount,
			&i.FollowerCount,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeRestaurantManager = `-- name: RemoveRestaurantManager :exec
DELETE
FROM restaurant_manager
WHERE restaurant_id = $1
  AND user_id = $2
`

type RemoveRestaurantManagerParams struct {
	RestaurantID int32  `json:"restaurantId"`
	UserID       string `json:"userId"`
}

func (q *Queries) RemoveRestaurantManager(ctx context.Context, db DBTX, arg *RemoveRestaurantManagerParams) error {
	_, err := db.Exec(ctx, removeRestaurantManager, arg.RestaurantID, arg.UserID)
	return err
}

const updateRestaurant = `-- name: UpdateRestaurant :one
UPDATE restaurants
SET name        = coalesce($1, name),
    description = coalesce($2, description),
    avatar_url  = coalesce($3, avatar_url),
    username    = coalesce($4, username),
    email       = coalesce($5, email),
    phone       = coalesce(sqlc('phone'), phone),
    address     = coalesce($6, address),
    lat         = coalesce($7, lat),
    lng         = coalesce($8, lng),
    is_approved = coalesce($9, is_approved),
    updated_at  = now()
WHERE id = $10 RETURNING id, name, description, avatar_url, username, email, phone, address, lat, lng, document, created_at, updated_at, is_approved, open_hour, website, cover_url
`

type UpdateRestaurantParams struct {
	Name         *string  `json:"name"`
	Description  *string  `json:"description"`
	AvatarUrl    *string  `json:"avatarUrl"`
	Username     *string  `json:"username"`
	Email        *string  `json:"email"`
	Address      *string  `json:"address"`
	Lat          *float64 `json:"lat"`
	Lng          *float64 `json:"lng"`
	IsApproved   *bool    `json:"isApproved"`
	RestaurantID int32    `json:"restaurantId"`
}

func (q *Queries) UpdateRestaurant(ctx context.Context, db DBTX, arg *UpdateRestaurantParams) (*Restaurant, error) {
	row := db.QueryRow(ctx, updateRestaurant,
		arg.Name,
		arg.Description,
		arg.AvatarUrl,
		arg.Username,
		arg.Email,
		arg.Address,
		arg.Lat,
		arg.Lng,
		arg.IsApproved,
		arg.RestaurantID,
	)
	var i Restaurant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.AvatarUrl,
		&i.Username,
		&i.Email,
		&i.Phone,
		&i.Address,
		&i.Lat,
		&i.Lng,
		&i.Document,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsApproved,
		&i.OpenHour,
		&i.Website,
		&i.CoverUrl,
	)
	return &i, err
}
