// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: restaurants.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addRestaurantManager = `-- name: AddRestaurantManager :exec
INSERT INTO restaurant_manager (restaurant_id, user_id, is_owner)
VALUES ($1::int, $2::varchar(64), $3::bool)
`

type AddRestaurantManagerParams struct {
	RestaurantID int32  `json:"restaurantId"`
	UserID       string `json:"userId"`
	IsOwner      bool   `json:"isOwner"`
}

func (q *Queries) AddRestaurantManager(ctx context.Context, db DBTX, arg *AddRestaurantManagerParams) error {
	_, err := db.Exec(ctx, addRestaurantManager, arg.RestaurantID, arg.UserID, arg.IsOwner)
	return err
}

const createRestaurant = `-- name: CreateRestaurant :one
INSERT INTO restaurants (name, description, avatar_url, username, email, phone, address, lat, lng, document)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, name, description, avatar_url, username, email, phone, address, lat, lng, document, created_at, updated_at, is_approved
`

type CreateRestaurantParams struct {
	Name        string   `json:"name"`
	Description *string  `json:"description"`
	AvatarUrl   *string  `json:"avatarUrl"`
	Username    string   `json:"username"`
	Email       *string  `json:"email"`
	Phone       *string  `json:"phone"`
	Address     *string  `json:"address"`
	Lat         *float64 `json:"lat"`
	Lng         *float64 `json:"lng"`
	Document    []byte   `json:"document"`
}

func (q *Queries) CreateRestaurant(ctx context.Context, db DBTX, arg *CreateRestaurantParams) (*Restaurant, error) {
	row := db.QueryRow(ctx, createRestaurant,
		arg.Name,
		arg.Description,
		arg.AvatarUrl,
		arg.Username,
		arg.Email,
		arg.Phone,
		arg.Address,
		arg.Lat,
		arg.Lng,
		arg.Document,
	)
	var i Restaurant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.AvatarUrl,
		&i.Username,
		&i.Email,
		&i.Phone,
		&i.Address,
		&i.Lat,
		&i.Lng,
		&i.Document,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsApproved,
	)
	return &i, err
}

const deleteRestaurant = `-- name: DeleteRestaurant :exec
DELETE FROM restaurants WHERE id = $1
`

func (q *Queries) DeleteRestaurant(ctx context.Context, db DBTX, id int32) error {
	_, err := db.Exec(ctx, deleteRestaurant, id)
	return err
}

const getManagingRestaurantByUser = `-- name: GetManagingRestaurantByUser :many
SELECT r.id, r.name, r.description, r.avatar_url, r.username, r.email, r.phone, r.address, r.lat, r.lng, r.document, r.created_at, r.updated_at, r.is_approved, rm.is_owner
FROM restaurant_manager rm
JOIN restaurants r ON rm.restaurant_id = r.id
WHERE rm.user_id = $1
`

type GetManagingRestaurantByUserRow struct {
	ID          int32              `json:"id"`
	Name        string             `json:"name"`
	Description *string            `json:"description"`
	AvatarUrl   *string            `json:"avatarUrl"`
	Username    string             `json:"username"`
	Email       *string            `json:"email"`
	Phone       *string            `json:"phone"`
	Address     *string            `json:"address"`
	Lat         *float64           `json:"lat"`
	Lng         *float64           `json:"lng"`
	Document    []byte             `json:"document"`
	CreatedAt   pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt   pgtype.Timestamptz `json:"updatedAt"`
	IsApproved  *bool              `json:"isApproved"`
	IsOwner     *bool              `json:"isOwner"`
}

func (q *Queries) GetManagingRestaurantByUser(ctx context.Context, db DBTX, userID interface{}) ([]*GetManagingRestaurantByUserRow, error) {
	rows, err := db.Query(ctx, getManagingRestaurantByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GetManagingRestaurantByUserRow{}
	for rows.Next() {
		var i GetManagingRestaurantByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.AvatarUrl,
			&i.Username,
			&i.Email,
			&i.Phone,
			&i.Address,
			&i.Lat,
			&i.Lng,
			&i.Document,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsApproved,
			&i.IsOwner,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRestaurantByID = `-- name: GetRestaurantByID :one
SELECT
    r.id,
    r.name,
    r.description,
    r.avatar_url,
    r.username,
    r.email,
    r.phone,
    r.address,
    r.lat,
    r.lng,
    r.created_at,
    r.updated_at
FROM restaurants r
WHERE id = $1
`

type GetRestaurantByIDRow struct {
	ID          int32              `json:"id"`
	Name        string             `json:"name"`
	Description *string            `json:"description"`
	AvatarUrl   *string            `json:"avatarUrl"`
	Username    string             `json:"username"`
	Email       *string            `json:"email"`
	Phone       *string            `json:"phone"`
	Address     *string            `json:"address"`
	Lat         *float64           `json:"lat"`
	Lng         *float64           `json:"lng"`
	CreatedAt   pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt   pgtype.Timestamptz `json:"updatedAt"`
}

func (q *Queries) GetRestaurantByID(ctx context.Context, db DBTX, id int32) (*GetRestaurantByIDRow, error) {
	row := db.QueryRow(ctx, getRestaurantByID, id)
	var i GetRestaurantByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.AvatarUrl,
		&i.Username,
		&i.Email,
		&i.Phone,
		&i.Address,
		&i.Lat,
		&i.Lng,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getRestaurantManagers = `-- name: GetRestaurantManagers :many
SELECT
    u.id,
    u.username,
    u.display_name,
    u.email,
    u.avatar_url,
    rm.restaurant_id,
    rm.is_owner
FROM restaurant_manager rm
JOIN users u ON rm.user_id = u.id
WHERE rm.restaurant_id = $1
`

type GetRestaurantManagersRow struct {
	ID           string  `json:"id"`
	Username     string  `json:"username"`
	DisplayName  string  `json:"displayName"`
	Email        string  `json:"email"`
	AvatarUrl    *string `json:"avatarUrl"`
	RestaurantID int32   `json:"restaurantId"`
	IsOwner      *bool   `json:"isOwner"`
}

func (q *Queries) GetRestaurantManagers(ctx context.Context, db DBTX, restaurantID int32) ([]*GetRestaurantManagersRow, error) {
	rows, err := db.Query(ctx, getRestaurantManagers, restaurantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GetRestaurantManagersRow{}
	for rows.Next() {
		var i GetRestaurantManagersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.DisplayName,
			&i.Email,
			&i.AvatarUrl,
			&i.RestaurantID,
			&i.IsOwner,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRestaurants = `-- name: GetRestaurants :many
SELECT
    r.id,
    r.name,
    r.description,
    r.avatar_url,
    r.username,
    r.email,
    r.phone,
    r.address,
    r.lat,
    r.lng,
    r.created_at,
    r.updated_at,
    r.is_approved
FROM restaurants r
LIMIT $1 OFFSET $2
`

type GetRestaurantsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type GetRestaurantsRow struct {
	ID          int32              `json:"id"`
	Name        string             `json:"name"`
	Description *string            `json:"description"`
	AvatarUrl   *string            `json:"avatarUrl"`
	Username    string             `json:"username"`
	Email       *string            `json:"email"`
	Phone       *string            `json:"phone"`
	Address     *string            `json:"address"`
	Lat         *float64           `json:"lat"`
	Lng         *float64           `json:"lng"`
	CreatedAt   pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt   pgtype.Timestamptz `json:"updatedAt"`
	IsApproved  *bool              `json:"isApproved"`
}

func (q *Queries) GetRestaurants(ctx context.Context, db DBTX, arg *GetRestaurantsParams) ([]*GetRestaurantsRow, error) {
	rows, err := db.Query(ctx, getRestaurants, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GetRestaurantsRow{}
	for rows.Next() {
		var i GetRestaurantsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.AvatarUrl,
			&i.Username,
			&i.Email,
			&i.Phone,
			&i.Address,
			&i.Lat,
			&i.Lng,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsApproved,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeRestaurantManager = `-- name: RemoveRestaurantManager :exec
DELETE FROM restaurant_manager
WHERE restaurant_id = $1 AND user_id = $2
`

type RemoveRestaurantManagerParams struct {
	RestaurantID int32       `json:"restaurantId"`
	UserID       interface{} `json:"userId"`
}

func (q *Queries) RemoveRestaurantManager(ctx context.Context, db DBTX, arg *RemoveRestaurantManagerParams) error {
	_, err := db.Exec(ctx, removeRestaurantManager, arg.RestaurantID, arg.UserID)
	return err
}

const updateRestaurant = `-- name: UpdateRestaurant :one
UPDATE restaurants
SET
    name = coalesce($1, name),
    description = coalesce($2, description),
    avatar_url = coalesce($3, avatar_url),
    username = coalesce($4, username),
    email = coalesce($5, email),
    phone = coalesce(sqlc('phone'), phone),
    address = coalesce($6, address),
    lat = coalesce($7, lat),
    lng = coalesce($8, lng),
    is_approved = coalesce($9, is_approved),
    updated_at = now()
WHERE id = $10
RETURNING id, name, description, avatar_url, username, email, phone, address, lat, lng, document, created_at, updated_at, is_approved
`

type UpdateRestaurantParams struct {
	Name         *string  `json:"name"`
	Description  *string  `json:"description"`
	AvatarUrl    *string  `json:"avatarUrl"`
	Username     *string  `json:"username"`
	Email        *string  `json:"email"`
	Address      *string  `json:"address"`
	Lat          *float64 `json:"lat"`
	Lng          *float64 `json:"lng"`
	IsApproved   *bool    `json:"isApproved"`
	RestaurantID int32    `json:"restaurantId"`
}

func (q *Queries) UpdateRestaurant(ctx context.Context, db DBTX, arg *UpdateRestaurantParams) (*Restaurant, error) {
	row := db.QueryRow(ctx, updateRestaurant,
		arg.Name,
		arg.Description,
		arg.AvatarUrl,
		arg.Username,
		arg.Email,
		arg.Address,
		arg.Lat,
		arg.Lng,
		arg.IsApproved,
		arg.RestaurantID,
	)
	var i Restaurant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.AvatarUrl,
		&i.Username,
		&i.Email,
		&i.Phone,
		&i.Address,
		&i.Lat,
		&i.Lng,
		&i.Document,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsApproved,
	)
	return &i, err
}
