// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: reviews.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createReview = `-- name: CreateReview :one
WITH inserted_review as (
    INSERT INTO reviews (rating, comment, user_id, dish_id)
        VALUES ($1::smallint,
                $2::text,
                $3::varchar(63),
                $4::int)
        RETURNING id, rating, comment, created_at, user_id, dish_id, updated_at)
SELECT r.id,
       r.comment,
       r.rating,
       r.dish_id,
       u.username,
       u.display_name as user_display_name,
       d.name         as dish_name
FROM inserted_review r
         LEFT JOIN users u on u.id = r.user_id
         LEFT JOIN dishes d on d.id = r.dish_id
`

type CreateReviewParams struct {
	Rating  *int16  `json:"rating"`
	Comment *string `json:"comment"`
	UserID  *string `json:"userId"`
	DishID  *int32  `json:"dishId"`
}

type CreateReviewRow struct {
	ID              int32   `json:"id"`
	Comment         string  `json:"comment"`
	Rating          int16   `json:"rating"`
	DishID          int32   `json:"dishId"`
	Username        *string `json:"username"`
	UserDisplayName *string `json:"userDisplayName"`
	DishName        *string `json:"dishName"`
}

func (q *Queries) CreateReview(ctx context.Context, db DBTX, arg *CreateReviewParams) (*CreateReviewRow, error) {
	row := db.QueryRow(ctx, createReview,
		arg.Rating,
		arg.Comment,
		arg.UserID,
		arg.DishID,
	)
	var i CreateReviewRow
	err := row.Scan(
		&i.ID,
		&i.Comment,
		&i.Rating,
		&i.DishID,
		&i.Username,
		&i.UserDisplayName,
		&i.DishName,
	)
	return &i, err
}

const deleteReview = `-- name: DeleteReview :exec
DELETE
FROM reviews
WHERE id = $1
`

func (q *Queries) DeleteReview(ctx context.Context, db DBTX, id int32) error {
	_, err := db.Exec(ctx, deleteReview, id)
	return err
}

const getReviews = `-- name: GetReviews :many
SELECT r.id,
       r.comment,
       r.rating,
       r.dish_id,
       d.name         as dish_name,
       d.images -> 0  as dish_image,
       r.user_id,
       u.username,
       u.avatar_url   as user_image,
       u.display_name as user_display_name,
       res.id as restaurant_id,
       res.username as restaurant_username,
       res.name as restaurant_name,
       r.created_at,
       r.updated_at
FROM reviews r
         LEFT JOIN dishes d on d.id = r.dish_id
         LEFT JOIN users u on r.user_id = u.id
         LEFT JOIN restaurants res on res.id = d.restaurant_id
WHERE ($3::bigint is null or r.dish_id = $3::bigint)
  and ($4::varchar(64) is null or r.user_id = $4::varchar(64))
  and ($5::int is null or d.restaurant_id = $5::int)
OFFSET $1 LIMIT $2
`

type GetReviewsParams struct {
	Offset       int32   `json:"offset"`
	Limit        int32   `json:"limit"`
	DishID       *int64  `json:"dishId"`
	UserID       *string `json:"userId"`
	RestaurantID *int32  `json:"restaurantId"`
}

type GetReviewsRow struct {
	ID                 int32              `json:"id"`
	Comment            string             `json:"comment"`
	Rating             int16              `json:"rating"`
	DishID             int32              `json:"dishId"`
	DishName           *string            `json:"dishName"`
	DishImage          interface{}        `json:"dishImage"`
	UserID             string             `json:"userId"`
	Username           *string            `json:"username"`
	UserImage          *string            `json:"userImage"`
	UserDisplayName    *string            `json:"userDisplayName"`
	RestaurantID       *int32             `json:"restaurantId"`
	RestaurantUsername *string            `json:"restaurantUsername"`
	RestaurantName     *string            `json:"restaurantName"`
	CreatedAt          pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt          pgtype.Timestamptz `json:"updatedAt"`
}

func (q *Queries) GetReviews(ctx context.Context, db DBTX, arg *GetReviewsParams) ([]*GetReviewsRow, error) {
	rows, err := db.Query(ctx, getReviews,
		arg.Offset,
		arg.Limit,
		arg.DishID,
		arg.UserID,
		arg.RestaurantID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GetReviewsRow{}
	for rows.Next() {
		var i GetReviewsRow
		if err := rows.Scan(
			&i.ID,
			&i.Comment,
			&i.Rating,
			&i.DishID,
			&i.DishName,
			&i.DishImage,
			&i.UserID,
			&i.Username,
			&i.UserImage,
			&i.UserDisplayName,
			&i.RestaurantID,
			&i.RestaurantUsername,
			&i.RestaurantName,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
