// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: users.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, username, email, display_name)
VALUES ($1::varchar(64),
        $2::varchar(64),
        $3::varchar(127),
        $4::varchar(255))
RETURNING id, username, email, display_name, avatar_url, lat, lng, budget, created_at, updated_at, enable
`

type CreateUserParams struct {
	ID          *string `json:"id"`
	Username    *string `json:"username"`
	Email       *string `json:"email"`
	DisplayName *string `json:"displayName"`
}

func (q *Queries) CreateUser(ctx context.Context, db DBTX, arg *CreateUserParams) (*User, error) {
	row := db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Username,
		arg.Email,
		arg.DisplayName,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Lat,
		&i.Lng,
		&i.Budget,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Enable,
	)
	return &i, err
}

const getUserById = `-- name: GetUserById :one
SELECT
    u.id,
    u.username,
    u.email,
    u.display_name,
    u.avatar_url,
    u.lat,
    u.lng,
    COALESCE(u.budget, 0) AS budget,
    u.created_at,
    u.updated_at,
    COUNT(r.id) AS review_count,
    COALESCE(AVG(r.rating), 0) AS average_rating,
    ARRAY_AGG(DISTINCT JSONB_BUILD_OBJECT(
            'id',   c.id,
            'name', c.name,
            'imageUrl', c.image_url
                       )) FILTER (
        WHERE
        c.name IS NOT NULL
        ) AS fav_cuisines
FROM
    users u
        LEFT JOIN reviews r ON r.user_id = u.id
        LEFT JOIN user_cuisine uc ON uc.user_id = u.id
        LEFT JOIN cuisines c ON c.id = uc.cuisine_id
WHERE
    u.id = $1 :: varchar(64)
GROUP BY
    u.id,
    u.username,
    u.email,
    u.display_name,
    u.avatar_url,
    u.lat,
    u.lng,
    u.budget,
    u.created_at,
    u.updated_at
`

type GetUserByIdRow struct {
	ID            string             `json:"id"`
	Username      string             `json:"username"`
	Email         string             `json:"email"`
	DisplayName   string             `json:"displayName"`
	AvatarUrl     *string            `json:"avatarUrl"`
	Lat           *float64           `json:"lat"`
	Lng           *float64           `json:"lng"`
	Budget        int64              `json:"budget"`
	CreatedAt     pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt     pgtype.Timestamptz `json:"updatedAt"`
	ReviewCount   int64              `json:"reviewCount"`
	AverageRating interface{}        `json:"averageRating"`
	FavCuisines   interface{}        `json:"favCuisines"`
}

func (q *Queries) GetUserById(ctx context.Context, db DBTX, id string) (*GetUserByIdRow, error) {
	row := db.QueryRow(ctx, getUserById, id)
	var i GetUserByIdRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Lat,
		&i.Lng,
		&i.Budget,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ReviewCount,
		&i.AverageRating,
		&i.FavCuisines,
	)
	return &i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT u.id,
       u.username,
       u.email,
       u.display_name,
       u.avatar_url,
       u.lat,
       u.lng,
       u.budget,
       u.created_at,
       u.updated_at,
       count(r.*)                 AS review_count,
       coalesce(avg(r.rating), 0) as average_rating
FROM users u
         LEFT JOIN reviews r ON u.id = r.user_id
WHERE u.username = $1::varchar(64)
GROUP BY u.id, u.username, u.email, u.display_name, u.avatar_url, u.created_at, u.updated_at
`

type GetUserByUsernameRow struct {
	ID            string             `json:"id"`
	Username      string             `json:"username"`
	Email         string             `json:"email"`
	DisplayName   string             `json:"displayName"`
	AvatarUrl     *string            `json:"avatarUrl"`
	Lat           *float64           `json:"lat"`
	Lng           *float64           `json:"lng"`
	Budget        *int64             `json:"budget"`
	CreatedAt     pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt     pgtype.Timestamptz `json:"updatedAt"`
	ReviewCount   int64              `json:"reviewCount"`
	AverageRating interface{}        `json:"averageRating"`
}

func (q *Queries) GetUserByUsername(ctx context.Context, db DBTX, username string) (*GetUserByUsernameRow, error) {
	row := db.QueryRow(ctx, getUserByUsername, username)
	var i GetUserByUsernameRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Lat,
		&i.Lng,
		&i.Budget,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ReviewCount,
		&i.AverageRating,
	)
	return &i, err
}

const updateUser = `-- name: UpdateUser :one
WITH updated_user AS (
    UPDATE users
        SET
            username = coalesce($1::varchar(64), username),
            email = coalesce($2::varchar(127), email),
            display_name = coalesce($3::varchar(255), display_name),
            avatar_url = coalesce($4::varchar(255), avatar_url),
            lat = coalesce($5::float8, lat),
            lng = coalesce($6::float8, lng),
            budget = coalesce($7::int8, budget),
            enable = coalesce($8::bool, enable),
            updated_at = now()
        WHERE id = $9::varchar(64)
        RETURNING id, username, email, display_name, avatar_url, lat, lng, budget, created_at, updated_at)
SELECT u.id,
       u.username,
       u.email,
       u.display_name,
       u.avatar_url,
       u.lat,
       u.lng,
       u.budget,
       u.created_at,
       u.updated_at,
       count(r.*)                 AS review_count,
       coalesce(avg(r.rating), 0) as average_rating
FROM updated_user u
         LEFT JOIN reviews r ON u.id = r.user_id
GROUP BY u.id,
         u.username,
         u.email,
         u.display_name,
         u.avatar_url,
         u.lat,
         u.lng,
         u.budget,
         u.created_at,
         u.updated_at
`

type UpdateUserParams struct {
	Username    *string  `json:"username"`
	Email       *string  `json:"email"`
	DisplayName *string  `json:"displayName"`
	AvatarUrl   *string  `json:"avatarUrl"`
	Lat         *float64 `json:"lat"`
	Lng         *float64 `json:"lng"`
	Budget      *int64   `json:"budget"`
	Enable      *bool    `json:"enable"`
	ID          *string  `json:"id"`
}

type UpdateUserRow struct {
	ID            string             `json:"id"`
	Username      string             `json:"username"`
	Email         string             `json:"email"`
	DisplayName   string             `json:"displayName"`
	AvatarUrl     *string            `json:"avatarUrl"`
	Lat           *float64           `json:"lat"`
	Lng           *float64           `json:"lng"`
	Budget        *int64             `json:"budget"`
	CreatedAt     pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt     pgtype.Timestamptz `json:"updatedAt"`
	ReviewCount   int64              `json:"reviewCount"`
	AverageRating interface{}        `json:"averageRating"`
}

func (q *Queries) UpdateUser(ctx context.Context, db DBTX, arg *UpdateUserParams) (*UpdateUserRow, error) {
	row := db.QueryRow(ctx, updateUser,
		arg.Username,
		arg.Email,
		arg.DisplayName,
		arg.AvatarUrl,
		arg.Lat,
		arg.Lng,
		arg.Budget,
		arg.Enable,
		arg.ID,
	)
	var i UpdateUserRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Lat,
		&i.Lng,
		&i.Budget,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ReviewCount,
		&i.AverageRating,
	)
	return &i, err
}
