// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: users.sql

package database

import (
	"context"
)

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, db DBTX, id interface{}) error {
	_, err := db.Exec(ctx, deleteUser, id)
	return err
}

const getUserByID = `-- name: GetUserByID :one
SELECT
    u.id,
    u.username,
    u.email,
    u.display_name,
    u.avatar_url
FROM users u
WHERE id = $1
`

type GetUserByIDRow struct {
	ID          interface{} `json:"id"`
	Username    string      `json:"username"`
	Email       string      `json:"email"`
	DisplayName string      `json:"displayName"`
	AvatarUrl   *string     `json:"avatarUrl"`
}

func (q *Queries) GetUserByID(ctx context.Context, db DBTX, id interface{}) (*GetUserByIDRow, error) {
	row := db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.DisplayName,
		&i.AvatarUrl,
	)
	return &i, err
}

const syncKCUser = `-- name: SyncKCUser :one
INSERT INTO users (id, username, email, display_name)
VALUES ($1, $2, $3, $4)
ON CONFLICT (id) DO UPDATE
    SET username = EXCLUDED.username,
        email = EXCLUDED.email,
        display_name = EXCLUDED.display_name
RETURNING id, username, email, display_name, avatar_url, lat, lng, budget, created_at, updated_at
`

type SyncKCUserParams struct {
	ID          interface{} `json:"id"`
	Username    string      `json:"username"`
	Email       string      `json:"email"`
	DisplayName string      `json:"displayName"`
}

func (q *Queries) SyncKCUser(ctx context.Context, db DBTX, arg *SyncKCUserParams) (*User, error) {
	row := db.QueryRow(ctx, syncKCUser,
		arg.ID,
		arg.Username,
		arg.Email,
		arg.DisplayName,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Lat,
		&i.Lng,
		&i.Budget,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
