// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package repo

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Food struct {
	ID           pgtype.UUID
	RestaurantID pgtype.UUID
	Name         string
	Description  pgtype.Text
	Price        pgtype.Numeric
	UpdatedAt    pgtype.Timestamp
}

type FoodReview struct {
	ReviewID int32
	DishID   pgtype.UUID
}

type FoodTag struct {
	ID               int32
	Name             pgtype.Text
	BriefDescription pgtype.Text
	TagID            pgtype.Int4
	FoodID           pgtype.UUID
}

type Post struct {
	ID                  int32
	AuthorID            pgtype.UUID
	CheckinRestaurantID pgtype.UUID
	Content             pgtype.Text
	CreatedAt           pgtype.Timestamp
	UpdatedAt           pgtype.Timestamp
}

type PostComment struct {
	ID             int32
	RefToCommentID pgtype.Int4
	PostID         pgtype.Int4
	AuthorID       pgtype.UUID
	Content        pgtype.Text
	CreatedAt      pgtype.Timestamp
	UpdatedAt      pgtype.Timestamp
}

type Profile struct {
	ID            pgtype.UUID
	ProfileType   string
	TagName       string
	Name          string
	Email         string
	PhoneNumber   pgtype.Text
	AvatarUrl     pgtype.Text
	Biography     pgtype.Text
	DetailAddress pgtype.Text
	LocalAddress  pgtype.Text
	Lat           pgtype.Float8
	Lng           pgtype.Float8
	CreatedAt     pgtype.Timestamp
	UpdatedAt     pgtype.Timestamp
	Enable        pgtype.Bool
}

type ProfileType struct {
	Code string
}

type Restaurant struct {
	ID             pgtype.UUID
	ProfileID      pgtype.UUID
	OperatingHours pgtype.Text
	CreatedAt      pgtype.Timestamp
	UpdatedAt      pgtype.Timestamp
}

type RestaurantManager struct {
	IsOwner      pgtype.Bool
	UserID       pgtype.UUID
	RestaurantID pgtype.UUID
}

type RestaurantTag struct {
	RestaurantID pgtype.UUID
	TagID        int32
}

type Review struct {
	ID           int32
	RestaurantID pgtype.UUID
	Content      pgtype.Text
	Author       pgtype.UUID
	Rate         pgtype.Int4
	CreatedAt    pgtype.Timestamp
	UpdatedAt    pgtype.Timestamp
}

type Tag struct {
	ID          int32
	TagType     pgtype.Text
	ImageUrl    pgtype.Text
	Name        string
	Slug        pgtype.Text
	Description pgtype.Text
}

type User struct {
	ID        pgtype.UUID
	ProfileID pgtype.UUID
	Dob       pgtype.Date
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type UserTag struct {
	UserID pgtype.UUID
	TagID  int32
}
