// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Food struct {
	ID           string           `json:"id"`
	RestaurantID string           `json:"restaurantId"`
	Name         string           `json:"name"`
	Description  *string          `json:"description"`
	Price        int32            `json:"price"`
	UpdatedAt    pgtype.Timestamp `json:"updatedAt"`
}

type FoodReview struct {
	ReviewID int32  `json:"reviewId"`
	DishID   string `json:"dishId"`
}

type FoodTag struct {
	ID               int32   `json:"id"`
	Name             *string `json:"name"`
	BriefDescription *string `json:"briefDescription"`
	TagID            *int32  `json:"tagId"`
	FoodID           *string `json:"foodId"`
}

type Post struct {
	ID                  int32            `json:"id"`
	AuthorID            *string          `json:"authorId"`
	CheckinRestaurantID *string          `json:"checkinRestaurantId"`
	Content             *string          `json:"content"`
	CreatedAt           pgtype.Timestamp `json:"createdAt"`
	UpdatedAt           pgtype.Timestamp `json:"updatedAt"`
}

type PostComment struct {
	ID             int32            `json:"id"`
	RefToCommentID *int32           `json:"refToCommentId"`
	PostID         *int32           `json:"postId"`
	AuthorID       *string          `json:"authorId"`
	Content        *string          `json:"content"`
	CreatedAt      pgtype.Timestamp `json:"createdAt"`
	UpdatedAt      pgtype.Timestamp `json:"updatedAt"`
}

type Profile struct {
	ID            string           `json:"id"`
	ProfileType   *string          `json:"profileType"`
	TagName       string           `json:"tagName"`
	Name          string           `json:"name"`
	Email         string           `json:"email"`
	PhoneNumber   *string          `json:"phoneNumber"`
	AvatarUrl     *string          `json:"avatarUrl"`
	Biography     *string          `json:"biography"`
	DetailAddress *string          `json:"detailAddress"`
	LocalAddress  *string          `json:"localAddress"`
	Lat           *float64         `json:"lat"`
	Lng           *float64         `json:"lng"`
	CreatedAt     pgtype.Timestamp `json:"createdAt"`
	UpdatedAt     pgtype.Timestamp `json:"updatedAt"`
	Enable        *bool            `json:"enable"`
}

type ProfileType struct {
	Code string `json:"code"`
}

type Restaurant struct {
	ID             string           `json:"id"`
	OperatingHours *string          `json:"operatingHours"`
	CreatedAt      pgtype.Timestamp `json:"createdAt"`
	UpdatedAt      pgtype.Timestamp `json:"updatedAt"`
}

type RestaurantManager struct {
	IsOwner      *bool  `json:"isOwner"`
	UserID       string `json:"userId"`
	RestaurantID string `json:"restaurantId"`
}

type RestaurantTag struct {
	RestaurantID string `json:"restaurantId"`
	TagID        int32  `json:"tagId"`
}

type Review struct {
	ID           int32            `json:"id"`
	RestaurantID *string          `json:"restaurantId"`
	Content      *string          `json:"content"`
	Author       *string          `json:"author"`
	Rate         *int32           `json:"rate"`
	CreatedAt    pgtype.Timestamp `json:"createdAt"`
	UpdatedAt    pgtype.Timestamp `json:"updatedAt"`
}

type Tag struct {
	ID          int32   `json:"id"`
	TagType     *string `json:"tagType"`
	ImageUrl    *string `json:"imageUrl"`
	Name        string  `json:"name"`
	Slug        *string `json:"slug"`
	Description *string `json:"description"`
}

type User struct {
	ID        string           `json:"id"`
	Dob       pgtype.Date      `json:"dob"`
	CreatedAt pgtype.Timestamp `json:"createdAt"`
	UpdatedAt pgtype.Timestamp `json:"updatedAt"`
}

type UserTag struct {
	UserID string `json:"userId"`
	TagID  int32  `json:"tagId"`
}
