// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: profiles.sql

package repository

import (
	"context"
)

const createProfile = `-- name: CreateProfile :one
INSERT INTO profiles (
    profile_type, tag_name, name, email, phone_number, avatar_url, biography,
    detail_address, local_address, lat, lng, enable
) VALUES (
             $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12
         ) RETURNING id, profile_type, tag_name, name, email, phone_number, avatar_url, biography, detail_address, local_address, lat, lng, created_at, updated_at, enable
`

type CreateProfileParams struct {
	ProfileType   *string  `json:"profileType"`
	TagName       string   `json:"tagName"`
	Name          string   `json:"name"`
	Email         string   `json:"email"`
	PhoneNumber   *string  `json:"phoneNumber"`
	AvatarUrl     *string  `json:"avatarUrl"`
	Biography     *string  `json:"biography"`
	DetailAddress *string  `json:"detailAddress"`
	LocalAddress  *string  `json:"localAddress"`
	Lat           *float64 `json:"lat"`
	Lng           *float64 `json:"lng"`
	Enable        *bool    `json:"enable"`
}

// CreateProfile
//
//	INSERT INTO profiles (
//	    profile_type, tag_name, name, email, phone_number, avatar_url, biography,
//	    detail_address, local_address, lat, lng, enable
//	) VALUES (
//	             $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12
//	         ) RETURNING id, profile_type, tag_name, name, email, phone_number, avatar_url, biography, detail_address, local_address, lat, lng, created_at, updated_at, enable
func (q *Queries) CreateProfile(ctx context.Context, db DBTX, arg *CreateProfileParams) (Profile, error) {
	row := db.QueryRow(ctx, createProfile,
		arg.ProfileType,
		arg.TagName,
		arg.Name,
		arg.Email,
		arg.PhoneNumber,
		arg.AvatarUrl,
		arg.Biography,
		arg.DetailAddress,
		arg.LocalAddress,
		arg.Lat,
		arg.Lng,
		arg.Enable,
	)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.ProfileType,
		&i.TagName,
		&i.Name,
		&i.Email,
		&i.PhoneNumber,
		&i.AvatarUrl,
		&i.Biography,
		&i.DetailAddress,
		&i.LocalAddress,
		&i.Lat,
		&i.Lng,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Enable,
	)
	return i, err
}

const deleteProfile = `-- name: DeleteProfile :exec
DELETE FROM profiles WHERE id = $1
`

// DeleteProfile
//
//	DELETE FROM profiles WHERE id = $1
func (q *Queries) DeleteProfile(ctx context.Context, db DBTX, id string) error {
	_, err := db.Exec(ctx, deleteProfile, id)
	return err
}

const getProfileByID = `-- name: GetProfileByID :one
SELECT id, profile_type, tag_name, name, email, phone_number, avatar_url, biography, detail_address, local_address, lat, lng, created_at, updated_at, enable FROM profiles WHERE id = $1
`

// GetProfileByID
//
//	SELECT id, profile_type, tag_name, name, email, phone_number, avatar_url, biography, detail_address, local_address, lat, lng, created_at, updated_at, enable FROM profiles WHERE id = $1
func (q *Queries) GetProfileByID(ctx context.Context, db DBTX, id string) (Profile, error) {
	row := db.QueryRow(ctx, getProfileByID, id)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.ProfileType,
		&i.TagName,
		&i.Name,
		&i.Email,
		&i.PhoneNumber,
		&i.AvatarUrl,
		&i.Biography,
		&i.DetailAddress,
		&i.LocalAddress,
		&i.Lat,
		&i.Lng,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Enable,
	)
	return i, err
}

const listProfiles = `-- name: ListProfiles :many
SELECT id, profile_type, tag_name, name, email, phone_number, avatar_url, biography, detail_address, local_address, lat, lng, created_at, updated_at, enable FROM profiles ORDER BY created_at DESC LIMIT $1 OFFSET $2
`

type ListProfilesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

// ListProfiles
//
//	SELECT id, profile_type, tag_name, name, email, phone_number, avatar_url, biography, detail_address, local_address, lat, lng, created_at, updated_at, enable FROM profiles ORDER BY created_at DESC LIMIT $1 OFFSET $2
func (q *Queries) ListProfiles(ctx context.Context, db DBTX, arg *ListProfilesParams) ([]Profile, error) {
	rows, err := db.Query(ctx, listProfiles, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Profile{}
	for rows.Next() {
		var i Profile
		if err := rows.Scan(
			&i.ID,
			&i.ProfileType,
			&i.TagName,
			&i.Name,
			&i.Email,
			&i.PhoneNumber,
			&i.AvatarUrl,
			&i.Biography,
			&i.DetailAddress,
			&i.LocalAddress,
			&i.Lat,
			&i.Lng,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Enable,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProfile = `-- name: UpdateProfile :exec
UPDATE profiles
SET name = $2, email = $3, phone_number = $4, avatar_url = $5, biography = $6,
    detail_address = $7, local_address = $8, lat = $9, lng = $10, updated_at = now(), enable = $11
WHERE id = $1
`

type UpdateProfileParams struct {
	ID            string   `json:"id"`
	Name          string   `json:"name"`
	Email         string   `json:"email"`
	PhoneNumber   *string  `json:"phoneNumber"`
	AvatarUrl     *string  `json:"avatarUrl"`
	Biography     *string  `json:"biography"`
	DetailAddress *string  `json:"detailAddress"`
	LocalAddress  *string  `json:"localAddress"`
	Lat           *float64 `json:"lat"`
	Lng           *float64 `json:"lng"`
	Enable        *bool    `json:"enable"`
}

// UpdateProfile
//
//	UPDATE profiles
//	SET name = $2, email = $3, phone_number = $4, avatar_url = $5, biography = $6,
//	    detail_address = $7, local_address = $8, lat = $9, lng = $10, updated_at = now(), enable = $11
//	WHERE id = $1
func (q *Queries) UpdateProfile(ctx context.Context, db DBTX, arg *UpdateProfileParams) error {
	_, err := db.Exec(ctx, updateProfile,
		arg.ID,
		arg.Name,
		arg.Email,
		arg.PhoneNumber,
		arg.AvatarUrl,
		arg.Biography,
		arg.DetailAddress,
		arg.LocalAddress,
		arg.Lat,
		arg.Lng,
		arg.Enable,
	)
	return err
}
