// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package repository

import (
	"context"
)

type Querier interface {
	//CreateFood
	//
	//  INSERT INTO foods (restaurant_id, name, description, price)
	//  VALUES ($1, $2, $3, $4) RETURNING id, restaurant_id, name, description, price, updated_at
	CreateFood(ctx context.Context, db DBTX, arg *CreateFoodParams) (Food, error)
	//CreateProfile
	//
	//  INSERT INTO profiles (
	//      profile_type, tag_name, name, email, phone_number, avatar_url, biography,
	//      detail_address, local_address, lat, lng, enable
	//  ) VALUES (
	//               $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12
	//           ) RETURNING id, profile_type, tag_name, name, email, phone_number, avatar_url, biography, detail_address, local_address, lat, lng, created_at, updated_at, enable
	CreateProfile(ctx context.Context, db DBTX, arg *CreateProfileParams) (Profile, error)
	//CreateRestaurant
	//
	//  INSERT INTO restaurants (id, operating_hours)
	//  VALUES ($1, $2) RETURNING id, operating_hours, created_at, updated_at
	CreateRestaurant(ctx context.Context, db DBTX, arg *CreateRestaurantParams) (Restaurant, error)
	//CreateReview
	//
	//  INSERT INTO reviews (restaurant_id, content, author, rate)
	//  VALUES ($1, $2, $3, $4) RETURNING id, restaurant_id, content, author, rate, created_at, updated_at
	CreateReview(ctx context.Context, db DBTX, arg *CreateReviewParams) (Review, error)
	//CreateUser
	//
	//  INSERT INTO users (id, dob) VALUES ($1, $2) RETURNING id, dob, created_at, updated_at
	CreateUser(ctx context.Context, db DBTX, arg *CreateUserParams) (User, error)
	//DeleteFood
	//
	//  DELETE FROM foods WHERE id = $1
	DeleteFood(ctx context.Context, db DBTX, id string) error
	//DeleteProfile
	//
	//  DELETE FROM profiles WHERE id = $1
	DeleteProfile(ctx context.Context, db DBTX, id string) error
	//DeleteRestaurant
	//
	//  DELETE FROM restaurants WHERE id = $1
	DeleteRestaurant(ctx context.Context, db DBTX, id string) error
	//DeleteReview
	//
	//  DELETE FROM reviews WHERE id = $1
	DeleteReview(ctx context.Context, db DBTX, id int32) error
	//DeleteUser
	//
	//  DELETE FROM users WHERE id = $1
	DeleteUser(ctx context.Context, db DBTX, id string) error
	//GetFoodByID
	//
	//  SELECT id, restaurant_id, name, description, price, updated_at FROM foods WHERE id = $1
	GetFoodByID(ctx context.Context, db DBTX, id string) (Food, error)
	//GetProfileByID
	//
	//  SELECT id, profile_type, tag_name, name, email, phone_number, avatar_url, biography, detail_address, local_address, lat, lng, created_at, updated_at, enable FROM profiles WHERE id = $1
	GetProfileByID(ctx context.Context, db DBTX, id string) (Profile, error)
	//GetRestaurantByID
	//
	//  SELECT id, operating_hours, created_at, updated_at FROM restaurants WHERE id = $1
	GetRestaurantByID(ctx context.Context, db DBTX, id string) (Restaurant, error)
	//GetReviewByID
	//
	//  SELECT id, restaurant_id, content, author, rate, created_at, updated_at FROM reviews WHERE id = $1
	GetReviewByID(ctx context.Context, db DBTX, id int32) (Review, error)
	//GetUserByID
	//
	//  SELECT id, dob, created_at, updated_at FROM users WHERE id = $1
	GetUserByID(ctx context.Context, db DBTX, id string) (User, error)
	//ListFoodsByRestaurant
	//
	//  SELECT id, restaurant_id, name, description, price, updated_at FROM foods WHERE restaurant_id = $1 ORDER BY updated_at DESC LIMIT $2 OFFSET $3
	ListFoodsByRestaurant(ctx context.Context, db DBTX, arg *ListFoodsByRestaurantParams) ([]Food, error)
	//ListProfiles
	//
	//  SELECT id, profile_type, tag_name, name, email, phone_number, avatar_url, biography, detail_address, local_address, lat, lng, created_at, updated_at, enable FROM profiles ORDER BY created_at DESC LIMIT $1 OFFSET $2
	ListProfiles(ctx context.Context, db DBTX, arg *ListProfilesParams) ([]Profile, error)
	//ListRestaurants
	//
	//  SELECT id, operating_hours, created_at, updated_at FROM restaurants ORDER BY created_at DESC LIMIT $1 OFFSET $2
	ListRestaurants(ctx context.Context, db DBTX, arg *ListRestaurantsParams) ([]Restaurant, error)
	//ListReviewsByRestaurant
	//
	//  SELECT id, restaurant_id, content, author, rate, created_at, updated_at FROM reviews WHERE restaurant_id = $1 ORDER BY created_at DESC LIMIT $2 OFFSET $3
	ListReviewsByRestaurant(ctx context.Context, db DBTX, arg *ListReviewsByRestaurantParams) ([]Review, error)
	//ListUsers
	//
	//  SELECT id, dob, created_at, updated_at FROM users ORDER BY created_at DESC LIMIT $1 OFFSET $2
	ListUsers(ctx context.Context, db DBTX, arg *ListUsersParams) ([]User, error)
	//UpdateFood
	//
	//  UPDATE foods SET name = $2, description = $3, price = $4, updated_at = now() WHERE id = $1
	UpdateFood(ctx context.Context, db DBTX, arg *UpdateFoodParams) error
	//UpdateProfile
	//
	//  UPDATE profiles
	//  SET name = $2, email = $3, phone_number = $4, avatar_url = $5, biography = $6,
	//      detail_address = $7, local_address = $8, lat = $9, lng = $10, updated_at = now(), enable = $11
	//  WHERE id = $1
	UpdateProfile(ctx context.Context, db DBTX, arg *UpdateProfileParams) error
	//UpdateRestaurant
	//
	//  UPDATE restaurants SET operating_hours = $2, updated_at = now() WHERE id = $1
	UpdateRestaurant(ctx context.Context, db DBTX, arg *UpdateRestaurantParams) error
	//UpdateReview
	//
	//  UPDATE reviews SET content = $2, rate = $3, updated_at = now() WHERE id = $1
	UpdateReview(ctx context.Context, db DBTX, arg *UpdateReviewParams) error
	//UpdateUser
	//
	//  UPDATE users SET dob = $2, updated_at = now() WHERE id = $1
	UpdateUser(ctx context.Context, db DBTX, arg *UpdateUserParams) error
}

var _ Querier = (*Queries)(nil)
