// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: restaurants.sql

package repository

import (
	"context"
)

const createRestaurant = `-- name: CreateRestaurant :one
INSERT INTO restaurants (id, operating_hours)
VALUES ($1, $2) RETURNING id, operating_hours, created_at, updated_at
`

type CreateRestaurantParams struct {
	ID             string  `json:"id"`
	OperatingHours *string `json:"operatingHours"`
}

// CreateRestaurant
//
//	INSERT INTO restaurants (id, operating_hours)
//	VALUES ($1, $2) RETURNING id, operating_hours, created_at, updated_at
func (q *Queries) CreateRestaurant(ctx context.Context, db DBTX, arg *CreateRestaurantParams) (Restaurant, error) {
	row := db.QueryRow(ctx, createRestaurant, arg.ID, arg.OperatingHours)
	var i Restaurant
	err := row.Scan(
		&i.ID,
		&i.OperatingHours,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteRestaurant = `-- name: DeleteRestaurant :exec
DELETE FROM restaurants WHERE id = $1
`

// DeleteRestaurant
//
//	DELETE FROM restaurants WHERE id = $1
func (q *Queries) DeleteRestaurant(ctx context.Context, db DBTX, id string) error {
	_, err := db.Exec(ctx, deleteRestaurant, id)
	return err
}

const getRestaurantByID = `-- name: GetRestaurantByID :one
SELECT id, operating_hours, created_at, updated_at FROM restaurants WHERE id = $1
`

// GetRestaurantByID
//
//	SELECT id, operating_hours, created_at, updated_at FROM restaurants WHERE id = $1
func (q *Queries) GetRestaurantByID(ctx context.Context, db DBTX, id string) (Restaurant, error) {
	row := db.QueryRow(ctx, getRestaurantByID, id)
	var i Restaurant
	err := row.Scan(
		&i.ID,
		&i.OperatingHours,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listRestaurants = `-- name: ListRestaurants :many
SELECT id, operating_hours, created_at, updated_at FROM restaurants ORDER BY created_at DESC LIMIT $1 OFFSET $2
`

type ListRestaurantsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

// ListRestaurants
//
//	SELECT id, operating_hours, created_at, updated_at FROM restaurants ORDER BY created_at DESC LIMIT $1 OFFSET $2
func (q *Queries) ListRestaurants(ctx context.Context, db DBTX, arg *ListRestaurantsParams) ([]Restaurant, error) {
	rows, err := db.Query(ctx, listRestaurants, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Restaurant{}
	for rows.Next() {
		var i Restaurant
		if err := rows.Scan(
			&i.ID,
			&i.OperatingHours,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRestaurant = `-- name: UpdateRestaurant :exec
UPDATE restaurants SET operating_hours = $2, updated_at = now() WHERE id = $1
`

type UpdateRestaurantParams struct {
	ID             string  `json:"id"`
	OperatingHours *string `json:"operatingHours"`
}

// UpdateRestaurant
//
//	UPDATE restaurants SET operating_hours = $2, updated_at = now() WHERE id = $1
func (q *Queries) UpdateRestaurant(ctx context.Context, db DBTX, arg *UpdateRestaurantParams) error {
	_, err := db.Exec(ctx, updateRestaurant, arg.ID, arg.OperatingHours)
	return err
}
