import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "@/styles/globals.css";
import {ThemeProvider} from "next-themes";
import {ReactNode} from "react";
import RootProviders from "@/app/providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const roboto = Roboto(
    {
        weight: "400",
        subsets: ["latin", "latin-ext"]
    }
)

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${roboto.className} antialiased`}
      ><RootProviders>
          {children}
      </RootProviders>
      </body>
    </html>
  );
}
