// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: foods.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createFood = `-- name: CreateFood :one
INSERT INTO foods (restaurant_id, name, description, price)
VALUES ($1, $2, $3, $4) RETURNING id, restaurant_id, name, description, price, updated_at
`

type CreateFoodParams struct {
	RestaurantID string
	Name         string
	Description  pgtype.Text
	Price        pgtype.Numeric
}

func (q *Queries) CreateFood(ctx context.Context, arg CreateFoodParams) (Food, error) {
	row := q.db.QueryRow(ctx, createFood,
		arg.RestaurantID,
		arg.Name,
		arg.Description,
		arg.Price,
	)
	var i Food
	err := row.Scan(
		&i.ID,
		&i.RestaurantID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteFood = `-- name: DeleteFood :exec
DELETE FROM foods WHERE id = $1
`

func (q *Queries) DeleteFood(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteFood, id)
	return err
}

const getFoodByID = `-- name: GetFoodByID :one
SELECT id, restaurant_id, name, description, price, updated_at FROM foods WHERE id = $1
`

func (q *Queries) GetFoodByID(ctx context.Context, id string) (Food, error) {
	row := q.db.QueryRow(ctx, getFoodByID, id)
	var i Food
	err := row.Scan(
		&i.ID,
		&i.RestaurantID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.UpdatedAt,
	)
	return i, err
}

const listFoodsByRestaurant = `-- name: ListFoodsByRestaurant :many
SELECT id, restaurant_id, name, description, price, updated_at FROM foods WHERE restaurant_id = $1 ORDER BY updated_at DESC LIMIT $2 OFFSET $3
`

type ListFoodsByRestaurantParams struct {
	RestaurantID string
	Limit        int32
	Offset       int32
}

func (q *Queries) ListFoodsByRestaurant(ctx context.Context, arg ListFoodsByRestaurantParams) ([]Food, error) {
	rows, err := q.db.Query(ctx, listFoodsByRestaurant, arg.RestaurantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Food{}
	for rows.Next() {
		var i Food
		if err := rows.Scan(
			&i.ID,
			&i.RestaurantID,
			&i.Name,
			&i.Description,
			&i.Price,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFood = `-- name: UpdateFood :exec
UPDATE foods SET name = $2, description = $3, price = $4, updated_at = now() WHERE id = $1
`

type UpdateFoodParams struct {
	ID          string
	Name        string
	Description pgtype.Text
	Price       pgtype.Numeric
}

func (q *Queries) UpdateFood(ctx context.Context, arg UpdateFoodParams) error {
	_, err := q.db.Exec(ctx, updateFood,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Price,
	)
	return err
}
