// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Food struct {
	ID           string
	RestaurantID string
	Name         string
	Description  pgtype.Text
	Price        pgtype.Numeric
	UpdatedAt    pgtype.Timestamp
}

type FoodReview struct {
	ReviewID int32
	DishID   string
}

type FoodTag struct {
	ID               int32
	Name             pgtype.Text
	BriefDescription pgtype.Text
	TagID            pgtype.Int4
	FoodID           pgtype.Text
}

type Post struct {
	ID                  int32
	AuthorID            pgtype.Text
	CheckinRestaurantID pgtype.Text
	Content             pgtype.Text
	CreatedAt           pgtype.Timestamp
	UpdatedAt           pgtype.Timestamp
}

type PostComment struct {
	ID             int32
	RefToCommentID pgtype.Int4
	PostID         pgtype.Int4
	AuthorID       pgtype.Text
	Content        pgtype.Text
	CreatedAt      pgtype.Timestamp
	UpdatedAt      pgtype.Timestamp
}

type Profile struct {
	ID            string
	ProfileType   pgtype.Text
	TagName       string
	Name          string
	Email         string
	PhoneNumber   pgtype.Text
	AvatarUrl     pgtype.Text
	Biography     pgtype.Text
	DetailAddress pgtype.Text
	LocalAddress  pgtype.Text
	Lat           pgtype.Float8
	Lng           pgtype.Float8
	CreatedAt     pgtype.Timestamp
	UpdatedAt     pgtype.Timestamp
	Enable        pgtype.Bool
}

type ProfileType struct {
	Code string
}

type Restaurant struct {
	ID             string
	OperatingHours pgtype.Text
	CreatedAt      pgtype.Timestamp
	UpdatedAt      pgtype.Timestamp
}

type RestaurantManager struct {
	IsOwner      pgtype.Bool
	UserID       string
	RestaurantID string
}

type RestaurantTag struct {
	RestaurantID string
	TagID        int32
}

type Review struct {
	ID           int32
	RestaurantID pgtype.Text
	Content      pgtype.Text
	Author       pgtype.Text
	Rate         pgtype.Int4
	CreatedAt    pgtype.Timestamp
	UpdatedAt    pgtype.Timestamp
}

type Tag struct {
	ID          int32
	TagType     pgtype.Text
	ImageUrl    pgtype.Text
	Name        string
	Slug        pgtype.Text
	Description pgtype.Text
}

type User struct {
	ID        string
	Dob       pgtype.Date
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type UserTag struct {
	UserID string
	TagID  int32
}
