// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: profiles.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProfile = `-- name: CreateProfile :one
INSERT INTO profiles (
    profile_type, tag_name, name, email, phone_number, avatar_url, biography,
    detail_address, local_address, lat, lng, enable
) VALUES (
             $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12
         ) RETURNING id, profile_type, tag_name, name, email, phone_number, avatar_url, biography, detail_address, local_address, lat, lng, created_at, updated_at, enable
`

type CreateProfileParams struct {
	ProfileType   pgtype.Text
	TagName       string
	Name          string
	Email         string
	PhoneNumber   pgtype.Text
	AvatarUrl     pgtype.Text
	Biography     pgtype.Text
	DetailAddress pgtype.Text
	LocalAddress  pgtype.Text
	Lat           pgtype.Float8
	Lng           pgtype.Float8
	Enable        pgtype.Bool
}

func (q *Queries) CreateProfile(ctx context.Context, arg CreateProfileParams) (Profile, error) {
	row := q.db.QueryRow(ctx, createProfile,
		arg.ProfileType,
		arg.TagName,
		arg.Name,
		arg.Email,
		arg.PhoneNumber,
		arg.AvatarUrl,
		arg.Biography,
		arg.DetailAddress,
		arg.LocalAddress,
		arg.Lat,
		arg.Lng,
		arg.Enable,
	)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.ProfileType,
		&i.TagName,
		&i.Name,
		&i.Email,
		&i.PhoneNumber,
		&i.AvatarUrl,
		&i.Biography,
		&i.DetailAddress,
		&i.LocalAddress,
		&i.Lat,
		&i.Lng,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Enable,
	)
	return i, err
}

const deleteProfile = `-- name: DeleteProfile :exec
DELETE FROM profiles WHERE id = $1
`

func (q *Queries) DeleteProfile(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteProfile, id)
	return err
}

const getProfileByID = `-- name: GetProfileByID :one
SELECT id, profile_type, tag_name, name, email, phone_number, avatar_url, biography, detail_address, local_address, lat, lng, created_at, updated_at, enable FROM profiles WHERE id = $1
`

func (q *Queries) GetProfileByID(ctx context.Context, id string) (Profile, error) {
	row := q.db.QueryRow(ctx, getProfileByID, id)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.ProfileType,
		&i.TagName,
		&i.Name,
		&i.Email,
		&i.PhoneNumber,
		&i.AvatarUrl,
		&i.Biography,
		&i.DetailAddress,
		&i.LocalAddress,
		&i.Lat,
		&i.Lng,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Enable,
	)
	return i, err
}

const listProfiles = `-- name: ListProfiles :many
SELECT id, profile_type, tag_name, name, email, phone_number, avatar_url, biography, detail_address, local_address, lat, lng, created_at, updated_at, enable FROM profiles ORDER BY created_at DESC LIMIT $1 OFFSET $2
`

type ListProfilesParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListProfiles(ctx context.Context, arg ListProfilesParams) ([]Profile, error) {
	rows, err := q.db.Query(ctx, listProfiles, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Profile{}
	for rows.Next() {
		var i Profile
		if err := rows.Scan(
			&i.ID,
			&i.ProfileType,
			&i.TagName,
			&i.Name,
			&i.Email,
			&i.PhoneNumber,
			&i.AvatarUrl,
			&i.Biography,
			&i.DetailAddress,
			&i.LocalAddress,
			&i.Lat,
			&i.Lng,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Enable,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProfile = `-- name: UpdateProfile :exec
UPDATE profiles
SET name = $2, email = $3, phone_number = $4, avatar_url = $5, biography = $6,
    detail_address = $7, local_address = $8, lat = $9, lng = $10, updated_at = now(), enable = $11
WHERE id = $1
`

type UpdateProfileParams struct {
	ID            string
	Name          string
	Email         string
	PhoneNumber   pgtype.Text
	AvatarUrl     pgtype.Text
	Biography     pgtype.Text
	DetailAddress pgtype.Text
	LocalAddress  pgtype.Text
	Lat           pgtype.Float8
	Lng           pgtype.Float8
	Enable        pgtype.Bool
}

func (q *Queries) UpdateProfile(ctx context.Context, arg UpdateProfileParams) error {
	_, err := q.db.Exec(ctx, updateProfile,
		arg.ID,
		arg.Name,
		arg.Email,
		arg.PhoneNumber,
		arg.AvatarUrl,
		arg.Biography,
		arg.DetailAddress,
		arg.LocalAddress,
		arg.Lat,
		arg.Lng,
		arg.Enable,
	)
	return err
}
