// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"context"
)

type Querier interface {
	CreateFood(ctx context.Context, arg CreateFoodParams) (Food, error)
	CreateProfile(ctx context.Context, arg CreateProfileParams) (Profile, error)
	CreateRestaurant(ctx context.Context, arg CreateRestaurantParams) (Restaurant, error)
	CreateReview(ctx context.Context, arg CreateReviewParams) (Review, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteFood(ctx context.Context, id string) error
	DeleteProfile(ctx context.Context, id string) error
	DeleteRestaurant(ctx context.Context, id string) error
	DeleteReview(ctx context.Context, id int32) error
	DeleteUser(ctx context.Context, id string) error
	GetFoodByID(ctx context.Context, id string) (Food, error)
	GetProfileByID(ctx context.Context, id string) (Profile, error)
	GetRestaurantByID(ctx context.Context, id string) (Restaurant, error)
	GetReviewByID(ctx context.Context, id int32) (Review, error)
	GetUserByID(ctx context.Context, id string) (User, error)
	ListFoodsByRestaurant(ctx context.Context, arg ListFoodsByRestaurantParams) ([]Food, error)
	ListProfiles(ctx context.Context, arg ListProfilesParams) ([]Profile, error)
	ListRestaurants(ctx context.Context, arg ListRestaurantsParams) ([]Restaurant, error)
	ListReviewsByRestaurant(ctx context.Context, arg ListReviewsByRestaurantParams) ([]Review, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	UpdateFood(ctx context.Context, arg UpdateFoodParams) error
	UpdateProfile(ctx context.Context, arg UpdateProfileParams) error
	UpdateRestaurant(ctx context.Context, arg UpdateRestaurantParams) error
	UpdateReview(ctx context.Context, arg UpdateReviewParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) error
}

var _ Querier = (*Queries)(nil)
