// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: restaurants.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRestaurant = `-- name: CreateRestaurant :one
INSERT INTO restaurants (id, operating_hours)
VALUES ($1, $2) RETURNING id, operating_hours, created_at, updated_at
`

type CreateRestaurantParams struct {
	ID             string
	OperatingHours pgtype.Text
}

func (q *Queries) CreateRestaurant(ctx context.Context, arg CreateRestaurantParams) (Restaurant, error) {
	row := q.db.QueryRow(ctx, createRestaurant, arg.ID, arg.OperatingHours)
	var i Restaurant
	err := row.Scan(
		&i.ID,
		&i.OperatingHours,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteRestaurant = `-- name: DeleteRestaurant :exec
DELETE FROM restaurants WHERE id = $1
`

func (q *Queries) DeleteRestaurant(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteRestaurant, id)
	return err
}

const getRestaurantByID = `-- name: GetRestaurantByID :one
SELECT id, operating_hours, created_at, updated_at FROM restaurants WHERE id = $1
`

func (q *Queries) GetRestaurantByID(ctx context.Context, id string) (Restaurant, error) {
	row := q.db.QueryRow(ctx, getRestaurantByID, id)
	var i Restaurant
	err := row.Scan(
		&i.ID,
		&i.OperatingHours,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listRestaurants = `-- name: ListRestaurants :many
SELECT id, operating_hours, created_at, updated_at FROM restaurants ORDER BY created_at DESC LIMIT $1 OFFSET $2
`

type ListRestaurantsParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListRestaurants(ctx context.Context, arg ListRestaurantsParams) ([]Restaurant, error) {
	rows, err := q.db.Query(ctx, listRestaurants, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Restaurant{}
	for rows.Next() {
		var i Restaurant
		if err := rows.Scan(
			&i.ID,
			&i.OperatingHours,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRestaurant = `-- name: UpdateRestaurant :exec
UPDATE restaurants SET operating_hours = $2, updated_at = now() WHERE id = $1
`

type UpdateRestaurantParams struct {
	ID             string
	OperatingHours pgtype.Text
}

func (q *Queries) UpdateRestaurant(ctx context.Context, arg UpdateRestaurantParams) error {
	_, err := q.db.Exec(ctx, updateRestaurant, arg.ID, arg.OperatingHours)
	return err
}
