// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: reviews.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createReview = `-- name: CreateReview :one
INSERT INTO reviews (restaurant_id, content, author, rate)
VALUES ($1, $2, $3, $4) RETURNING id, restaurant_id, content, author, rate, created_at, updated_at
`

type CreateReviewParams struct {
	RestaurantID pgtype.Text
	Content      pgtype.Text
	Author       pgtype.Text
	Rate         pgtype.Int4
}

func (q *Queries) CreateReview(ctx context.Context, arg CreateReviewParams) (Review, error) {
	row := q.db.QueryRow(ctx, createReview,
		arg.RestaurantID,
		arg.Content,
		arg.Author,
		arg.Rate,
	)
	var i Review
	err := row.Scan(
		&i.ID,
		&i.RestaurantID,
		&i.Content,
		&i.Author,
		&i.Rate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteReview = `-- name: DeleteReview :exec
DELETE FROM reviews WHERE id = $1
`

func (q *Queries) DeleteReview(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteReview, id)
	return err
}

const getReviewByID = `-- name: GetReviewByID :one
SELECT id, restaurant_id, content, author, rate, created_at, updated_at FROM reviews WHERE id = $1
`

func (q *Queries) GetReviewByID(ctx context.Context, id int32) (Review, error) {
	row := q.db.QueryRow(ctx, getReviewByID, id)
	var i Review
	err := row.Scan(
		&i.ID,
		&i.RestaurantID,
		&i.Content,
		&i.Author,
		&i.Rate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listReviewsByRestaurant = `-- name: ListReviewsByRestaurant :many
SELECT id, restaurant_id, content, author, rate, created_at, updated_at FROM reviews WHERE restaurant_id = $1 ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type ListReviewsByRestaurantParams struct {
	RestaurantID pgtype.Text
	Limit        int32
	Offset       int32
}

func (q *Queries) ListReviewsByRestaurant(ctx context.Context, arg ListReviewsByRestaurantParams) ([]Review, error) {
	rows, err := q.db.Query(ctx, listReviewsByRestaurant, arg.RestaurantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Review{}
	for rows.Next() {
		var i Review
		if err := rows.Scan(
			&i.ID,
			&i.RestaurantID,
			&i.Content,
			&i.Author,
			&i.Rate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateReview = `-- name: UpdateReview :exec
UPDATE reviews SET content = $2, rate = $3, updated_at = now() WHERE id = $1
`

type UpdateReviewParams struct {
	ID      int32
	Content pgtype.Text
	Rate    pgtype.Int4
}

func (q *Queries) UpdateReview(ctx context.Context, arg UpdateReviewParams) error {
	_, err := q.db.Exec(ctx, updateReview, arg.ID, arg.Content, arg.Rate)
	return err
}
