// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: reviews.sql

package db

import (
	"context"
)

const createReview = `-- name: CreateReview :one
INSERT INTO reviews (restaurant_id, content, author, rate)
VALUES ($1, $2, $3, $4) RETURNING id, restaurant_id, content, author, rate, created_at, updated_at
`

type CreateReviewParams struct {
	RestaurantID *string `json:"restaurantId"`
	Content      *string `json:"content"`
	Author       *string `json:"author"`
	Rate         *int32  `json:"rate"`
}

func (q *Queries) CreateReview(ctx context.Context, db DBTX, arg *CreateReviewParams) (*Review, error) {
	row := db.QueryRow(ctx, createReview,
		arg.RestaurantID,
		arg.Content,
		arg.Author,
		arg.Rate,
	)
	var i Review
	err := row.Scan(
		&i.ID,
		&i.RestaurantID,
		&i.Content,
		&i.Author,
		&i.Rate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const deleteReview = `-- name: DeleteReview :exec
DELETE FROM reviews WHERE id = $1
`

func (q *Queries) DeleteReview(ctx context.Context, db DBTX, id int32) error {
	_, err := db.Exec(ctx, deleteReview, id)
	return err
}

const getReviewByID = `-- name: GetReviewByID :one
SELECT id, restaurant_id, content, author, rate, created_at, updated_at FROM reviews WHERE id = $1
`

func (q *Queries) GetReviewByID(ctx context.Context, db DBTX, id int32) (*Review, error) {
	row := db.QueryRow(ctx, getReviewByID, id)
	var i Review
	err := row.Scan(
		&i.ID,
		&i.RestaurantID,
		&i.Content,
		&i.Author,
		&i.Rate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const listReviewsByRestaurant = `-- name: ListReviewsByRestaurant :many
SELECT id, restaurant_id, content, author, rate, created_at, updated_at FROM reviews WHERE restaurant_id = $1 ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type ListReviewsByRestaurantParams struct {
	RestaurantID *string `json:"restaurantId"`
	Limit        int32   `json:"limit"`
	Offset       int32   `json:"offset"`
}

func (q *Queries) ListReviewsByRestaurant(ctx context.Context, db DBTX, arg *ListReviewsByRestaurantParams) ([]*Review, error) {
	rows, err := db.Query(ctx, listReviewsByRestaurant, arg.RestaurantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Review{}
	for rows.Next() {
		var i Review
		if err := rows.Scan(
			&i.ID,
			&i.RestaurantID,
			&i.Content,
			&i.Author,
			&i.Rate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateReview = `-- name: UpdateReview :exec
UPDATE reviews SET content = $2, rate = $3, updated_at = now() WHERE id = $1
`

type UpdateReviewParams struct {
	ID      int32   `json:"id"`
	Content *string `json:"content"`
	Rate    *int32  `json:"rate"`
}

func (q *Queries) UpdateReview(ctx context.Context, db DBTX, arg *UpdateReviewParams) error {
	_, err := db.Exec(ctx, updateReview, arg.ID, arg.Content, arg.Rate)
	return err
}
