// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, dob) VALUES ($1, $2) RETURNING id, dob, created_at, updated_at
`

type CreateUserParams struct {
	ID  string      `json:"id"`
	Dob pgtype.Date `json:"dob"`
}

func (q *Queries) CreateUser(ctx context.Context, db DBTX, arg *CreateUserParams) (*User, error) {
	row := db.QueryRow(ctx, createUser, arg.ID, arg.Dob)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Dob,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, db DBTX, id string) error {
	_, err := db.Exec(ctx, deleteUser, id)
	return err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, dob, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, db DBTX, id string) (*User, error) {
	row := db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Dob,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, dob, created_at, updated_at FROM users ORDER BY created_at DESC LIMIT $1 OFFSET $2
`

type ListUsersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListUsers(ctx context.Context, db DBTX, arg *ListUsersParams) ([]*User, error) {
	rows, err := db.Query(ctx, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Dob,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :exec
UPDATE users SET dob = $2, updated_at = now() WHERE id = $1
`

type UpdateUserParams struct {
	ID  string      `json:"id"`
	Dob pgtype.Date `json:"dob"`
}

func (q *Queries) UpdateUser(ctx context.Context, db DBTX, arg *UpdateUserParams) error {
	_, err := db.Exec(ctx, updateUser, arg.ID, arg.Dob)
	return err
}
