host: "192.168.100.145"
port: 5432
user: "egourmet"
password: "egourmet"
dbname: "egourmet"
sslmode: "disable"
connect-timeout: 60
pool-max-conns: 20
pool-min-conns: 2
pool-max-conn-idle-time: "10m"
pool-max-conn-lifetime: "30m"
pool-health-check-period: "5m"
pool-max-conn-lifetime-jitter: "5m"