driver: "postgres"          # Database driver (e.g., postgres, mysql)
host: "127.0.0.1"           # Database server address
port: 5432                  # Database port (default for PostgreSQL)
user: "egourmet"           # Database username
password: "egourmet"   # Database password
dbname: "egourmet"     # Database name
sslmode: "disable"          # SSL mode (disable, require, verify-ca, verify-full)
connect-timeout: 60
# Connection pool settings
pool-max-conns: 20           # Maximum number of connections in the pool
pool-min-conns: 2            # Minimum number of active connections
# Connection timeout settings
pool-max-conn-idle-time: "10m"    # Max idle time for connections (e.g., 10m, 30s)
pool-max-conn-lifetime: "30m"     # Max lifetime for a connection before recycling
# Advanced settings
pool-health-check-period: "5m"   # Interval for health checks on idle connections
pool-max-conn-lifetime-jitter: "5m"
duration-threshold: "100ms"